### ISSUE TITLE
in Node::~Node why n->control_deps.clear() is not called?

### ISSUE THREAD

**Issue by hpsoar** [dmlc/nnvm#139]
I noted that n->inputs.clear() is called,
don't quite understand why n->control_deps.clear() is not called.

thank you~

**Comment by jermainewang** [comment]
Actually, it doesn't matter. The nodes in the loop will be deleted after the destruction, so the input entry vector and control_dep vector will all be cleared anyway. I agree it is much clearer to either explicitly have both of them cleared or leave them to be cleared by the destruction.
