### ISSUE TITLE
'Tuple' type of fields are lost in the list from MXListAllOpNames()

### ISSUE THREAD

**Issue by pierric** [dmlc/nnvm#150]
Here is some symbol info from MXSymbolGetAtomicSymbolInfo()
```
# _contrib_MultiBoxDetection, argc=10
arg:           cls_prob | NDArray-or-Symbol
arg:           loc_pred | NDArray-or-Symbol
arg:             anchor | NDArray-or-Symbol
arg:               clip | boolean, optional, default=True
arg:          threshold | float, optional, default=0.01
arg:      background_id | int, optional, default='0'
arg:      nms_threshold | float, optional, default=0.5
arg:     force_suppress | boolean, optional, default=False
arg:          variances | , optional, default=(0.1,0.1,0.2,0.2)
arg:           nms_topk | int, optional, default='-1'
```
the argument "variances" has no type there. 

I think there is some information lost for the compiler when it sees "Tuple" (include/nnvm/tuple.h). Should call DMLC_DECLARE_TYPE_NAME to specialize the `const char* type_name<Type>()`

**Comment by tqchen** [comment]
good cAtch, can you submit a pr for this ?

**Comment by pierric** [comment]
sure, I will do. just come up with two questions
1. do we declare the tuple type for all of the following: float, double, int, uint32_t, uint64_t, std::string, bool? and any else?
2. what about naming them "tuple-of-" + Value's type name ?

**Comment by tqchen** [comment]
I think we only need to do it for most common ones, TShape, and tuple of int

**Comment by tqchen** [comment]
I think tuple of works for me, we can also reuse the type_name traits to get the type of content type

**Comment by pierric** [comment]
done in #151
