### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by cudawarped** [dmlc/nnvm#159]
Hi, as above I have tried to install with Anaconda 3 on windows after "successfully" building the libs in VS2015.  Unfortunately python is not my first language so I may not have done this correctly because when I try to import nnvm.compiler I get the following error

ValueError: Cannot find global function nnvm.graph._move_module

Is this a configuration issue and if so is it easy to fix?
Thank you.

**Comment by tqchen** [comment]
The cmake NNVM compiler do not yet support windows, we are looking into a possible solution

**Comment by tqchen** [comment]
checkout the instruction after https://github.com/dmlc/nnvm/pull/161 is merged in

**Comment by cudawarped** [comment]
Hi, thank you for the quick response, I am really looking forward to getting this working, but I am still having problems.

I have rebuilt and installed tvm from the nnvm subfolder without errors, however I am getting unresolved external symbol errors like the one below when building nnvm in release x64 with visual studio 2015 community update 3 on windows 8.1:

> 3>compile_engine.obj : error LNK2019: unresolved external symbol "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl Halide::operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,struct Halide::Type const &)" (??6Halide@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV12@AEBUType@0@@Z) referenced in function "int __cdecl nnvm::compiler::GetTypeFlag(struct Halide::Type)" (?GetTypeFlag@compiler@nnvm@@YAHUType@Halide@@@Z)

**Comment by tqchen** [comment]
Yes, use of llvm is necessary because some part of the preprocessing uses cpu code
