### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by GarrickLin** [dmlc/nnvm#162]
I tried to build nnvm in Windows 10, and there was an error as following:
```
-- Build with TVM libary: E:/workspace/cpp/nnvm/tvm/build/Release/tvm.lib
CMake Error at CMakeLists.txt:108 (install):
  install Library TARGETS given no DESTINATION!
```

**Comment by GarrickLin** [comment]
I reference [this page](https://stackoverflow.com/questions/14990343/cmake-error-targets-given-no-library-destination-for-shared-library-target) to modify
```
line 108   install(TARGETS nnvm LIBRARY DESTINATION lib)
```
to
```
line 108   install(TARGETS nnvm ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
```
 and it works now

**Comment by cudawarped** [comment]
Hi, can you now successfully build the nnvm_compiler.dll?  I am getting lots of unresolved symbol errors like below
`1>compile_engine.obj : error LNK2019: unresolved external symbol "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl Halide::operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,struct Halide::Type const &)" (??6Halide@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV12@AEBUType@0@@Z) referenced in function "int __cdecl nnvm::compiler::GetTypeFlag(struct Halide::Type)" (?GetTypeFlag@compiler@nnvm@@YAHUType@Halide@@@Z)`

**Comment by GarrickLin** [comment]
@cudawarped I can build `nnvm_compiler.dll` successfully. Did you use the proper version of VS2015?

**Comment by cudawarped** [comment]
Thanks GarrickLin, I am not sure what I was doing incorrectly, but I started the build again from scratch using your fix above, and everything built successfully.
