### ISSUE TITLE
Support Go language.

### ISSUE THREAD

**Issue by njnest** [dmlc/nnvm#168]
Hello guys, what about Go?

**Comment by tqchen** [comment]
It should be possible to support a go runtime for TVM, as we did for [javascript](https://github.com/dmlc/tvm/tree/master/web), [java](https://github.com/dmlc/tvm/tree/master/jvm) based on the C API

This allows deployment of tvm compiled modules with GO. As far as I know there is no one working on this so contribution is welcomed

**Comment by PENGUINLIONG** [comment]
Should all language support be provided in this repo? Isn't it better to separate them into different repositories, especially for those have their own package managers?

**Comment by tqchen** [comment]
close for now, will open a new issue if there is a proposal on doing so
