### ISSUE TITLE
[WINDOWS] Error when trying to export_library

### ISSUE THREAD

**Issue by cudawarped** [dmlc/nnvm#169]
I get the following error when running the get_started.py example

> Traceback (most recent call last):
  File "get_started.py", line 132, in <module>
    lib.export_library(path_lib)
  File "C:\Users\b8\Anaconda3\lib\site-packages\tvm-0.1.0-py3.6-win-amd64.egg\tv
m\module.py", line 108, in export_library
    fcompile(file_name, files, **kwargs)
  File "C:\Users\b8\Anaconda3\lib\site-packages\tvm-0.1.0-py3.6-win-amd64.egg\tv
m\contrib\cc.py", line 48, in create_shared
    msg += out
TypeError: must be str, not bytes

I get the same error from create_shared when running the get_started.py example from tvm.  Is this a windows issue or have I build/installed tvm/nnvm incorrectly?

Thank you.

**Comment by tqchen** [comment]
it is not yet supported, see progress in here https://github.com/dmlc/tvm/pull/531

**Comment by tqchen** [comment]
should be fixed by https://github.com/dmlc/tvm/pull/531
