### ISSUE TITLE
[OP] Support ELU

### ISSUE THREAD

**Issue by edmBernard** [dmlc/nnvm#171]
As nnvm is used as Mxnet backend I was thinking all mxnet operator was compatible with nnvm.
I try to use nnvm with tvm to deploy network and I got this error about elu activation ? 
I use `leaky_relu` with `elu` parameter.

```bash
NotImplementedError: act_type: elu is not supported in nnvm.
```

Does I need to implement it ? Or it exist but I do something wrong ?

**Comment by tqchen** [comment]
@zhreshold can you look into this?

**Comment by zhreshold** [comment]
@tqchen Are you supposing using this kind of composing operators?
```
elu(x) = - alpha * relu(1 - exp(x)) + relu(x)
```
This seems to be a bit over complicated for a single operator.

**Comment by tqchen** [comment]
It is fine since NNVM compiler automatically fuses and generated a fused kernel

**Comment by zhreshold** [comment]
Okay, I will take care of it. Probably I need to refactor some part to make it work for now and future.

**Comment by edmBernard** [comment]
@zhreshold thank's for your work.
