### ISSUE TITLE
have some problem with get_start.py when using target= llvm

### ISSUE THREAD

**Issue by gengtsh** [dmlc/nnvm#176]
hi, here is my problem:
environment: virtual machine ubuntu 17. 
python version: 3.6
when i try to run get_start.py, i change target type from cuda to llvm 

the change in get_start.py lists here: 
deploy_graph, lib, params = nnvm.compiler.build(  compute_graph, target="llvm", shape={"x": shape}, dtype="float32")

my output:
graph_attr_keys = [storage_num_not_allocated, dtype, dltype, shape, storage_allocated_bytes, storage_id, storage_inplace_index]
-------deploy library-------
Traceback (most recent call last):
  File "get_started1.py", line 68, in <module>
    print(lib.imported_modules[0].get_source())
IndexError: list index out of range

it looks like they didn't allocated memory when i using llvm as my target.
then i comment "print(deploy_graph.ir())" and let the code move on
i get: 
-------deploy library-------
Traceback (most recent call last):
  File "get_started1.py", line 68, in <module>
    print(lib.imported_modules[0].get_source())
IndexError: list index out of range
then the problem is still be in libmod (tvm.Module).

i will appreciate if you can help me out. I want to use llvm lib, but i don't know what's wrong with this.

**Comment by tqchen** [comment]
This is because for llvm as a target, there will be no imported_modules, you can just do lib.get_source() to get the source of llvm

**Comment by tqchen** [comment]
For GPU targets, there are two components:
- The host library(in this case lib)
- the device library( lib.imported_modules[0])

**Comment by gengtsh** [comment]
thanks you so much for your prompt reply.
could you please tell me whether there is a doc to explain the relationship between target and lib or i need to go over the code to find it ?
And now, i have three problems:
1. Is "deploy_graph.ir()" also related to GPU target?
because i get : 
     graph_attr_keys = [storage_num_not_allocated, dtype, dltype, shape, storage_allocated_bytes,         storage_id, storage_inplace_index]

2. when i want to use llvm module, which option i should put into **graph_runtime.create(deploy_graph, lib, xxx*

3. when i use lib.get_source(), i get the following errors:

@__TVMAPISetLastError = linkonce dllexport local_unnamed_addr global void (i8*)* null, align 8
@.str = private constant [75 x i8] c"Assert fail: (num_args == 3), fuse_sqrt_elemwise_add: num_args should be 3\00", align 1
@.str.1 = private constant [105 x i8] c"Assert fail: tvm_handle_is_null(arg0.strides), arg0.strides: expected to be nullptr for contiguous array\00", align 1
@.str.2 = private constant [105 x i8] c"Assert fail: tvm_handle_is_null(arg1.strides), arg1.strides: expected to be nullptr for contiguous array\00", align 1
...
define dllexport i32 @fuse_sqrt_elemwise_add(i8* noalias nocapture readonly, i8* noalias nocapture readonly, i32) local_unnamed_addr {
entry:
  %3 = icmp eq i32 %2, 3
  br i1 %3, label %assert_end, label %assert_fail, !prof !0

assert_fail:                                      ; preds = %entry
  %4 = load void (i8*)*, void (i8*)** @__TVMAPISetLastError, align 8, !tbaa !1
  tail call void %4(i8* getelementptr inbounds ([75 x i8], [75 x i8]* @.str, i64 0, i64 0))
  ret i32 -1

assert_end:                                       ; preds = %entry
  %5 = bitcast i8* %0 to %0**
  %6 = load %0*, %0** %5, align 8
  %7 = bitcast i8* %1 to i32*
  %8 = load i32, i32* %7, align 4, !tbaa !4
  %9 = getelementptr inbounds i8, i8* %1, i64 4
  %10 = bitcast i8* %9 to i32*
  %11 = load i32, i32* %10, align 4, !tbaa !18
  %12 = getelementptr inbounds i8, i8* %0, i64 16
  %13 = bitcast i8* %12 to %0**
  %14 = load %0*, %0** %13, align 8
  %15 = getelementptr inbounds i8, i8* %1, i64 8
  %16 = bitcast i8* %15 to i32*
  %17 = load i32, i32* %16, align 4, !tbaa !20
  %18 = getelementptr inbounds %0, %0* %6, i64 0, i32 0
  %19 = load i8*, i8** %18, align 8
  %20 = getelementptr inbounds %0, %0* %6, i64 0, i32 4
  %21 = load i64*, i64** %20, align 8
  %22 = getelementptr inbounds %0, %0* %6, i64 0, i32 5
  %23 = load i64*, i64** %22, align 8
  %24 = icmp eq i64* %23, null
  br i1 %24, label %assert_end2, label %assert_fail1, !prof !0

assert_fail1:                                     ; preds = %assert_end
  %25 = load void (i8*)*, void (i8*)** @__TVMAPISetLastError, align 8, !tbaa !1
  tail call void %25(i8* getelementptr inbounds ([105 x i8], [105 x i8]* @.str.1, i64 0, i64 0))
  ret i32 -1

assert_end2:                         
...
...
; Function Attrs: nounwind readnone speculatable
declare float @llvm.sqrt.f32(float) #1

attributes #0 = { noinline nounwind }
attributes #1 = { nounwind readnone speculatable }

!0 = !{!"branch_weights", i32 1048576, i32 1}
!1 = !{!2, !2, i64 0}
!2 = !{!"ctx_ptr", !3, i64 0}
!3 = !{!"tvm-tbaa"}
!4 = !{!5, !5, i64 0}
....

**Comment by tqchen** [comment]
deploy graph have nothing to do with gpu target. To use llvm module, you can just pass the same thing to graph runtime using graph_runtime.create, no need to change any code.   lib.get_source is not error. it is the llvm IR that is the source code generated in host module

**Comment by gengtsh** [comment]
using llvm, the problem are: 

1. when i print : print(compute_graph.ir()) 

 i get :  graph_attr_keys = [**storage_num_not_allocated,** dtype, dltype, shape, storage_allocated_bytes, storage_id, storage_inplace_index]
here: storage_num_not_allocated. it didn't allocate memory for the input x and y
And i get huge amount of errors.
e.g:
@__TVMAPISetLastError = linkonce dllexport local_unnamed_addr global void (i8*)* null, align 8
@.str = private constant [75 x i8] c"Assert fail: (num_args == 3), fuse_sqrt_elemwise_add: num_args should be 3\00", align 1

2. i don't have GPU

original code in get_start: 
module = graph_runtime.create(deploy_graph, lib, tvm.gpu(0))
i think i need to change tvm.gpu() to llvm or some other,
if i didn't change tvm.gpu(0), i will get errors:  
[20:18:19] tvm/dmlc-core/include/dmlc/logging.h:308: [20:18:19] src/runtime/c_runtime_api.cc:83: Check failed: allow_missing Device API gpu is not enabled.

**Comment by tqchen** [comment]
change tvm.gpu(0) ->tvm.cpu(0)

**Comment by gengtsh** [comment]
it works, thanks a lot. 

Could you please tell me how i can handle this situation? thanks in advance.

@__TVMAPISetLastError = linkonce dllexport local_unnamed_addr global void (i8*)* null, align 8
@.str = private constant [75 x i8] c"Assert fail: (num_args == 3), fuse_sqrt_elemwise_add: num_args should be 3\00", align 1

**Comment by tqchen** [comment]
this is not error message. It is error handling code embedded in the generated library

**Comment by gengtsh** [comment]
got it. thanks
