### ISSUE TITLE
Could NNVM support the conversion of SVM in mlmodel to nnvm graph IR?

### ISSUE THREAD

**Issue by chenkandewang** [dmlc/nnvm#179]
Hi, I have a question about format support of NNVM. Since mlmodel may include general ML algorithms such as SVM in addition to NN, do you have any plans to support SVM in this project? Thank you!

**Comment by tqchen** [comment]
No, it only support neuralnets

**Comment by nouiz** [comment]
There was an SVM that was done with Theano. I'm pretty sure this
implementation could fix in nnvm too. But maybe not all SVM and I don't
have any information about how efficient it was. Just in case it would help.

**Comment by chenkandewang** [comment]
@tqchen @nouiz Thank you both.
