### ISSUE TITLE
Problem with Anaconda/Miniconda

### ISSUE THREAD

**Issue by imai-lm** [dmlc/nnvm#183]
I cannot import nnvm package under Anaconda/Miniconda python environment. When I import nnvm package, an error like `OSError: /root/.local/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/libnnvm_compiler.so: undefined symbol: _ZTIN3tvm4NodeE` occurs. Whichever the Python version is 2.x or 3.x, it happens.
To explain more in detail, I made a docker repo. See: https://hub.docker.com/r/imailm/nnvm-miniconda/
With the image, you can see the situation like the following.
```
root@d92c930dae2f:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@d92c930dae2f:/# python --version
Python 2.7.13 :: Anaconda, Inc.
root@d92c930dae2f:/# python -c 'import nnvm'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.local/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/__init__.py", line 6, in <module>
    from . import _base
  File "/root/.local/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/_base.py", line 47, in <module>
    _LIB = _load_lib()
  File "/root/.local/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/_base.py", line 39, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/opt/conda/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /root/.local/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/libnnvm_compiler.so: undefined symbol: _ZTIN3tvm4NodeE
```
While the docker image is with Miniconda/Python 2.7, the similar phenomenon also happens with my MacBook with Anaconda/Python 3.5:

```(anaconda3-4.2.0) LM-MacBook-27:nnvm imai$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13
BuildVersion:	17A405
(anaconda3-4.2.0) LM-MacBook-27:nnvm imai$ python --version
Python 3.5.2 :: Anaconda 4.2.0 (x86_64)
(anaconda3-4.2.0) LM-MacBook-27:nnvm imai$ python -c 'import nnvm'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/imai/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/__init__.py", line 6, in <module>
    from . import _base
  File "/Users/imai/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/_base.py", line 47, in <module>
    _LIB = _load_lib()
  File "/Users/imai/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/_base.py", line 39, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/Users/imai/.pyenv/versions/anaconda3-4.2.0/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/imai/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/libnnvm_compiler.dylib, 6): Symbol not found: __ZTIN3tvm4NodeE
  Referenced from: /Users/imai/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/libnnvm_compiler.dylib
  Expected in: flat namespace
 in /Users/imai/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/libnnvm_compiler.dylib
```

**Comment by PENGUINLIONG** [comment]
Check out [this one](https://github.com/vadimcn/vscode-lldb/issues/37) although it's unrelated to NNVM. There may be some relationship. It seems Anaconda has really poor interoperability.

**Comment by imai-lm** [comment]
@PENGUINLIONG Hmm, I failed to get the relationship... What is that? Anaconda causes some problem(s) about environment variables?

**Comment by PENGUINLIONG** [comment]
That's an example that Anaconda failed with non-python-native parts I recently found.

> Here's quick sum up of this thread for Windows users:
> * Anaconda and other non-official CPython distros are not working despite same version number (I've tested it few mins ago, seems like Anaconda adds/modify something in python environment). Someone with deeper knowlege of how things work could find a solution, but for the time being it's no-go. Another solution might be to re-build LLVM with Anaconda Python.
> * You need official CPython 3.5.x bundle.
> * You need LLVM 5+ with same build architecture as CPython.
> * You need to use Rust GNU toolchain with same build architecture.
> * You need to setup additional python env variables:
> ```
> PYTHONHOME=C:\Program Files (x86)\Python35-32
> PYTHONPATH=C:\Program Files (x86)\Python35-32\Lib\site-packages;C:\Program Files (x86)\Python35-32;C:\Program Files (x86)\Python35-32\Lib
> PYTHON_HOME=C:\Program Files (x86)\Python35-32
> ```
> As well as LLVM and Python should be in PATH.

According to these information, you can try:

* Use MinGW to build NNVM, TVM and so on.
* Update CPython.
* Set up env vars like in the quotes.

**Comment by imai-lm** [comment]
So you mean that even with Anaconda, I need to install another Python (CPython)? Currently, I am trying only with Anaconda.

**Comment by tqchen** [comment]
close due to in-activity, feel free to reopen

**Comment by douzsh** [comment]
I got the same problem when I build nnvm on my server.
I can't find tvm4Node function definition in all the codes..

**Comment by bonotake** [comment]
I tried this again, and found that this was only because tvm (and topi) was not correctly installed.
Sorry, but I was a newbie at that time...

**Comment by maitek** [comment]
Had a similar problem with nnvm/libnnvm_compiler.so: undefined symbol: _ZTIN3tvm4NodeE. Turned out that the git submodules were not loaded. Remeber to use --recursive when cloning the repository.

**Comment by chenqy4933** [comment]
What a pity there is not a solution above before the topic is closed!!!!!!!!!!!!
I meet this problem,finely it is becuse I forget to install the tvm and the topi,i think the nnvm folder include the tvm and topi.so I pass it ,what a big pity,so many people know it ,but no answer!!!

**Comment by PENGUINLIONG** [comment]
I didn't realize the problems actually come from git submodules. Sorry for that.

Here are some tips for those who still confused by NNVM-unrelated issues. Hope them could find this post. Of course, you should refer to the [installtion guide](https://github.com/dmlc/nnvm/blob/master/docs/how_to/install.md) in the first place.

## Cloning from Github

Remember to clone from Github remote with flag `--recursive` on; otherwise, the necessary submodules will not be loaded.

```sh
git clone --recursive https://github.com/dmlc/nnvm.git
```

If you *did forgot* to clone recursively, you don't have to re-clone the repository. Submodules can be initialized with:

```sh
cd nnvm
git submodule update --init --recursive
```

## Build NNVM

Once NNVM and its submodules are ready to go, we can start building it. Build TVM first, then NNVM. You should see the directory `tvm` in your cloned NNVM:

To build a package, enter the package directory and use CMake the project:

```sh
cmake .. -G "Visual Studio 15 2017 Win64"
cmake --build . --config Release
```

If you are not using VS2017, change the generator to something else.

**Comment by sott0n** [comment]
I have same problem that is `Symbol not found` when dlopen `lib/libnnvm_compiler.dylib` on Anaconda at MacOS. I tried install firstly nvm, and then nnvm. but this problem wasn't fix ...  
So, is there already a solution this problem ?
