### ISSUE TITLE
model_zoo/super_resolution.onnx is not legal

### ISSUE THREAD

**Issue by imai-lm** [dmlc/nnvm#185]
I guess [`tests/python/frontend/onnx/model_zoo/super_resolution.onnx`](https://github.com/dmlc/nnvm/blob/master/tests/python/frontend/onnx/model_zoo/super_resolution.onnx) should be a model in ONNX format, but it doesn't pass the current ONNX checker (ver 0.2).

Suppose the code `check.py` like the following:
```python
import onnx


print('ONNX version: ' + onnx.__version__)
model = onnx.load('super_resolution.onnx')
try:
    onnx.checker.check_model(model)
    print('valid model.')
except ValueError as e:
    print(e)
```
This produces an exception like this:
```
$ python check.py
ONNX version: 0.2
The model does not have an ir_version set properly.
```

**Comment by tqchen** [comment]
close this as we moved discussion to #186
