### ISSUE TITLE
onnx.load() outputs a model, not a graph... doesn't it?

### ISSUE THREAD

**Issue by imai-lm** [dmlc/nnvm#186]
I guess the following part of code is wrong:
https://github.com/dmlc/nnvm/blob/69bea128fcd7d06a130160d66a6f2c33e4bfd5e9/tests/python/frontend/onnx/test_graph.py#L8-L9
This produces an error, like `AttributeError: 'ModelProto' object has no attribute 'initializer'`. 
I guess It should be:
```
 onnx_model = onnx.load(onnx_file) 
 onnx_sym, params = nnvm.frontend.from_onnx(onnx_model.graph) 
```
This produces another error, though. 

p.s. The version of ONNX is 0.2.

**Comment by PENGUINLIONG** [comment]
That's right, you can PR it. Why these tests haven't been run so far...

BTW, What's the new error produced?

**Comment by imai-lm** [comment]
> BTW, What's the new error produced?

When I just ran it as it is, an IndexError occured:
```
python nnvm/tests/python/frontend/onnx/test_graph.py
Traceback (most recent call last):
  File "nnvm/tests/python/frontend/onnx/test_graph.py", line 24, in <module>
    test_super_resolution_example()
  File "nnvm/tests/python/frontend/onnx/test_graph.py", line 21, in test_super_resolution_example
    compare_graph(fname, symbol, ishape=(1, 1, 224, 224))
  File "nnvm/tests/python/frontend/onnx/test_graph.py", line 9, in compare_graph
    onnx_sym, params = nnvm.frontend.from_onnx(onnx_model.graph)
  File "/root/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/frontend/onnx.py", line 397, in from_onnx
    sym, params = g.from_onnx(graph)
  File "/root/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/frontend/onnx.py", line 284, in from_onnx
    out = out[0]
IndexError: list index out of range
```
But this is because the loaded model (`onnx_file`) is bad (see #185). So I tried it with a model that is exported from PyTorch, TypeError occured like:
```
Traceback (most recent call last):
  File "nnvm-onnx-import.py", line 10, in <module>
    sym, params = nnvm.frontend.from_onnx(model.graph)
  File "/Users/imai/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/frontend/onnx.py", line 397, in from_onnx
    sym, params = g.from_onnx(graph)
  File "/Users/imai/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/frontend/onnx.py", line 248, in from_onnx
    if i in self._params:
  File "/Users/imai/.pyenv/versions/3.5.3/lib/python3.5/site-packages/google/protobuf/message.py", line 83, in __hash__
    raise TypeError('unhashable object')
TypeError: unhashable object
```
Note that the environments are different.

**Comment by imai-lm** [comment]
Sorry, the test file itself was different: The `nnvm-onnx-import.py` was like:
```
import onnx
import nnvm
import nnvm.frontend
import nnvm.compiler
import tvm
from tvm.contrib import graph_runtime


model = onnx.load('alexnet.proto')
sym, params = nnvm.frontend.from_onnx(model.graph)
```
The `alexnet.proto` is the file I exported from a PyTorch model (which is 244MB, too large to share here).

**Comment by PENGUINLIONG** [comment]
It was [protobuf](https://github.com/google/protobuf/blob/09e0dbcf8f8a078070921e18b0592dbe7f9628df/python/google/protobuf/message.py#L83`). According to [python docs](https://docs.python.org/3/reference/datamodel.html#object.__eq__):

> User-defined classes have __eq__() and __hash__() methods by default; with them, all objects compare unequal (except with themselves) and x.__hash__() returns an appropriate value such that x == y implies both that x is y and hash(x) == hash(y).

Protobuf simply disabled users from comparing message objects, as well as from using the `in` operator we used here.

**Comment by imai-lm** [comment]
I understand the situation.  The type of `GraphProto.input` changed from `string` to a messagr type `ValueInfoProto` [18 days ago](https://github.com/onnx/onnx/commit/bbfad7dc9c2426655eed035f215f35d3b16f7656#diff-55a1ff6cfca1e1c4845ce400a29d1557R165). So now `onnx.py` cannot use `in` operator [here](https://github.com/dmlc/nnvm/blob/master/python/nnvm/frontend/onnx.py#L248).

**Comment by imai-lm** [comment]
I tried to fix the problem. I converted `i`s of `ValueInfoProto` around there to `i.name`. This seems to work, but then another (and a bigger) error occured:
```
Traceback (most recent call last):
  File "import.py", line 10, in <module>
    sym, params = nnvm.frontend.from_onnx(model.graph)
  File "/root/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/frontend/onnx.py", line 397, in from_onnx
    sym, params = g.from_onnx(graph)
  File "/root/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/frontend/onnx.py", line 266, in from_onnx
    new_op, new_attr = _convert_operator(op_name, attr)
  File "/root/.local/lib/python3.5/site-packages/nnvm-0.8.0-py3.5.egg/nnvm/frontend/onnx.py", line 206, in _convert_oper
ator
    raise NotImplementedError("Operator {} not implemented.".format(op_name))
NotImplementedError: Operator Gemm not implemented.
```
So now we have to add conversion(s) to [`_convert_map`](https://github.com/dmlc/nnvm/blob/master/python/nnvm/frontend/onnx.py#L102)...

**Comment by tqchen** [comment]
@zhreshold can you comment a bit on how we can support the Gemm?

**Comment by zhreshold** [comment]
So basically Gemm == sym.dense(use_bias=False), adding it to the _convert_map should work.

**Comment by tqchen** [comment]
plus there is transpose flag that need to be taken care of? Also @zhreshold I think we should not include the model file themselves in the future, but consider download and cache models when possible

**Comment by zhreshold** [comment]
Generating onnx model at runtime would be a better way, since they are changing all the time.

**Comment by tqchen** [comment]
I see it might make sense to do so for one model or so

**Comment by tqchen** [comment]
closing this for now. let us open another issue for fixing the gemm

**Comment by tqchen** [comment]
#189
