### ISSUE TITLE
[WINDOWS] Which tvm commit to use?

### ISSUE THREAD

**Issue by cudawarped** [dmlc/nnvm#188]
When I perform git submodule update --recursive following a pull in the nnvm repo, tvm is set to

> Submodule path 'tvm': checked out 'eb761f36302d24c740b77281ecdcdddb588edf36'

and not its latest commit, is this the correct commit, because get the following linking error when compiling nnvm in Visual Stuidio 2015

> 1>compile_engine.obj : error LNK2019: unresolved external symbol "public: virtual bool const __cdecl tvm::Node::_DerivedFrom(unsigned int)const " (?_DerivedFrom@Node@tvm@@ueba?B_NI@Z) referenced in function "public: virtual bool const __cdecl nnvm::compiler::GraphCacheEntryNode::_DerivedFrom(unsigned int)const " (?_DerivedFrom@GraphCacheEntryNode@compiler@nnvm@@ueba?B_NI@Z)
1>graph_fuse.obj : error LNK2001: unresolved external symbol "public: virtual bool const __cdecl tvm::Node::_DerivedFrom(unsigned int)const " (?_DerivedFrom@Node@tvm@@ueba?B_NI@Z)
1>graph_hash.obj : error LNK2001: unresolved external symbol "public: virtual bool const __cdecl tvm::Node::_DerivedFrom(unsigned int)const " (?_DerivedFrom@Node@tvm@@ueba?B_NI@Z)
1>packed_func_ext.obj : error LNK2001: unresolved external symbol "public: virtual bool const __cdecl tvm::Node::_DerivedFrom(unsigned int)const " (?_DerivedFrom@Node@tvm@@ueba?B_NI@Z)
1>compile_engine.obj : error LNK2019: unresolved external symbol "public: static unsigned int __cdecl tvm::Node::TypeKey2Index(char const *)" (?TypeKey2Index@Node@tvm@@saipebd@Z) referenced in function "public: virtual unsigned int const __cdecl nnvm::compiler::GraphCacheEntryNode::type_index(void)const " (?type_index@GraphCacheEntryNode@compiler@nnvm@@ueba?BIXZ)
1>graph_fuse.obj : error LNK2001: unresolved external symbol "public: static unsigned int __cdecl tvm::Node::TypeKey2Index(char const *)" (?TypeKey2Index@Node@tvm@@saipebd@Z)
1>graph_hash.obj : error LNK2001: unresolved external symbol "public: static unsigned int __cdecl tvm::Node::TypeKey2Index(char const *)" (?TypeKey2Index@Node@tvm@@saipebd@Z)
1>packed_func_ext.obj : error LNK2001: unresolved external symbol "public: static unsigned int __cdecl tvm::Node::TypeKey2Index(char const *)" (?TypeKey2Index@Node@tvm@@saipebd@Z)
1>compile_engine.obj : error LNK2019: unresolved external symbol "public: static char const * __cdecl tvm::Node::TypeIndex2Key(unsigned int)" (?TypeIndex2Key@Node@tvm@@sapebdi@Z) referenced in function "public: class tvm::IRFunctor<void __cdecl(class tvm::NodeRef const &,class Halide::Internal::IRPrinter *)> & __cdecl tvm::IRFunctor<void __cdecl(class tvm::NodeRef const &,class Halide::Internal::IRPrinter *)>::set_dispatch(class std::function<void __cdecl(class tvm::NodeRef const &,class Halide::Internal::IRPrinter *)>)" (??$set_dispatch@UGraphFuncNode@compiler@nnvm@@@?$IRFunctor@$$A6AXAEBVNodeRef@tvm@@peavirprinter@Internal@Halide@@@z@tvm@@qeaaaeav01@V?$function@$$A6AXAEBVNodeRef@tvm@@peavirprinter@Internal@Halide@@@z@std@@@z)
1>graph_hash.obj : error LNK2001: unresolved external symbol "public: static char const * __cdecl tvm::Node::TypeIndex2Key(unsigned int)" (?TypeIndex2Key@Node@tvm@@sapebdi@Z)

**Comment by PENGUINLIONG** [comment]
Have you compiled TVM? You should compile TVM first following the [TVM installation guide](https://github.com/dmlc/tvm/blob/master/docs/how_to/install.md). If you need Python interface, don't forget to install their Python packages.

Also, as I can remember, you should CMake-build dmlc-core first to build TVM successfully.

**Comment by cudawarped** [comment]
I have build tvm, and successfully run the get_started.py without any errors.  

Before updating to commit 'eb761f36302d24c740b77281ecdcdddb588edf36' I could also build nnvm without errors as well.  As nnvm seems to point to that commit I was wondering if that is the correct one to use, or should I use the latest one?

**Comment by PENGUINLIONG** [comment]
TVM should be backward compatible, i.e., new versions of TVM should do the same things as before. So if you want to use a newer version, just go ahead. The commit NNVM locked is simply 'the earliest version of TVM that NNVM will certainly work properly with.'

**Comment by PENGUINLIONG** [comment]
You should check the __update number__ of your Visual Studio 2015. As the [installation guide](https://github.com/dmlc/nnvm/blob/master/docs/how_to/install.md) read, it requires VS2015 __Update 3__. I tried building it with VS2015 __without Update__ and it failed, for 'unresolved symbols'. Now I am using VS2017, everything goes right.

**Comment by cudawarped** [comment]
Thank you, I have build with the latest version of tvm and nnvm with visual studio 2015 update 3 and I now get the following error when running the nnvm get_started.py

> Traceback (most recent call last):
  File "get_started.py", line 49, in <module>
    compute_graph, target="cuda", shape={"x": shape}, dtype="float32")
  File "C:\Users\b8\Anaconda3\lib\site-packages\nnvm-0.8.0-py3.5.egg\nnvm\compil
er\build_module.py", line 237, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "C:\Users\b8\Anaconda3\lib\site-packages\nnvm-0.8.0-py3.5.egg\nnvm\graph.
py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(g
handle)))
  File "C:\Users\b8\Anaconda3\lib\site-packages\nnvm-0.8.0-py3.5.egg\nnvm\_base.
py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "C:\Users\b8\Anaconda3\lib\site-packages\tvm-0.1.0-py3.5-win-amd64.egg\tv
m\_ffi\_ctypes\function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "C:\Users\b8\Anaconda3\lib\site-packages\nnvm-0.8.0-py3.5.egg\nnvm\top\te
nsor.py", line 14, in _schedule_injective
    return topi.generic.schedule_injective(outs)
AttributeError: module 'topi' has no attribute 'generic'

Are you able to run this sample when compiling with visual studio 2017?

**Comment by PENGUINLIONG** [comment]
Maybe you have missed a step: did you installed [`topi`](https://github.com/dmlc/tvm/blob/master/docs/how_to/install.md#python-package-installation)?

> ```shell
> cd topi/python; python setup.py install --user; cd ../..
> ```

**Comment by cudawarped** [comment]
Thank you, I have recompiled so many times I forgot that step.  All is working now, at least for resnet18_v1 models from mxnet.  With this latest build I am still unable to import any other Gluon models.  For vgg16 I get the following error, 

> Traceback (most recent call last):
  File "from_mxnet.py", line 71, in <module>
    graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=par
ams)
  File "C:\Users\b8\Anaconda3\lib\site-packages\nnvm-0.8.0-py3.5.egg\nnvm\compil
er\build_module.py", line 216, in build
    ishape, _ = graph_util.infer_shape(graph, **shape)
  File "C:\Users\b8\Anaconda3\lib\site-packages\nnvm-0.8.0-py3.5.egg\nnvm\compil
er\graph_util.py", line 28, in infer_shape
    graph = graph.apply("InferShape")
  File "C:\Users\b8\Anaconda3\lib\site-packages\nnvm-0.8.0-py3.5.egg\nnvm\graph.
py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(g
handle)))
  File "C:\Users\b8\Anaconda3\lib\site-packages\nnvm-0.8.0-py3.5.egg\nnvm\_base.
py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: Error in operator dense0: [17:31:57] D:\SSDBackup\Dev\Repo
s\nnvm\src\top\nn\nn.cc:44: Operator dense(units=4096, use_bias=True, name=dense0) expects weight's shape to be [4096,7], but got [4096,25088].

in from_mxnet.py, changing
`block = get_model('resnet18_v1', pretrained=True)`
to
`block = get_model('vgg16', pretrained=True)`
should I open up an issue for this?

**Comment by PENGUINLIONG** [comment]
It seems the shape of the first FC layer in pre-trained VGG16 model doesn't match the deduced one... No idea why it was that.

> should I open up an issue for this?

If you have done with the current topic (TVM commit), I think it's nice to close this issue and create another for the new topic.

**Comment by cudawarped** [comment]
Thank you for you help.
