### ISSUE TITLE
[WINDOWS] Error importing Gluon Model Zoo models

### ISSUE THREAD

**Issue by cudawarped** [dmlc/nnvm#190]
Hi, I can successfully run the from_mxnet.py example which uses the resnet18_v1 pre-trained model, however I have as yet been unable to use any other Gluon model zoo pre-trained models.

I have tried VGG16  by replacing
`block = get_model('resnet18_v1', pretrained=True)`
with
`block = get_model('vgg16', pretrained=True)`
but I get the following errors

> Traceback (most recent call last):
File "from_mxnet.py", line 71, in
graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=par
ams)
File "C:\Users\b8\Anaconda3\lib\site-packages\nnvm-0.8.0-py3.5.egg\nnvm\compil
er\build_module.py", line 216, in build
ishape, _ = graph_util.infer_shape(graph, **shape)
File "C:\Users\b8\Anaconda3\lib\site-packages\nnvm-0.8.0-py3.5.egg\nnvm\compil
er\graph_util.py", line 28, in infer_shape
graph = graph.apply("InferShape")
File "C:\Users\b8\Anaconda3\lib\site-packages\nnvm-0.8.0-py3.5.egg\nnvm\graph.
py", line 234, in apply
check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(g
handle)))
File "C:\Users\b8\Anaconda3\lib\site-packages\nnvm-0.8.0-py3.5.egg\nnvm_base.
py", line 72, in check_call
raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: Error in operator dense0: [17:31:57] D:\SSDBackup\Dev\Repo
s\nnvm\src\top\nn\nn.cc:44: Operator dense(units=4096, use_bias=True, name=dense0) expects weight's shape to be [4096,7], but got [4096,25088].

I am not that familiar with mxnet, (my plan would be to use it as an intermediary to use Keras models with nnvm) so I cannot understand why the model would expect an input dim of 7 to the dense layers?

**Comment by tqchen** [comment]
@zhreshold any thoughts? I guess there is something wrong happening during flatten or different set of input shape is expected?

**Comment by zhreshold** [comment]
What version of MXNET are you using?

**Comment by zhreshold** [comment]
@cudawarped I cannot reproduce the error.
Suppose you are using windows mxnet from pip install, you probably are using an pretty old version.
Try upgrade mxnet `pip install -U mxnet --pre` and see if the problem resolved.

**Comment by cudawarped** [comment]
Hi I upgraded

>   Found existing installation: mxnet 0.11.0
    Uninstalling mxnet-0.11.0:
      Successfully uninstalled mxnet-0.11.0
Successfully installed mxnet-0.12.0b20171020

but I still get the same error, is this likely to be a windows issue?

**Comment by zhreshold** [comment]
It is very unlikely related to system. First we need to make sure the versions are up to date.
@cudawarped  Can you update tvm as well?

**Comment by cudawarped** [comment]
@zhreshold I have updated 
tvm to 25f95766c9e7349dbc1874688fe92540a97712a6 - 25th Oct
nnvm to 4710d63d7fbcf02e23e55032461915e78d487737 - 24th Oct
mxnet to mxnet-0.12.0b20171025
With these updates I have no problem running get_started.py (tvm and nnvm) and from_mxnet.py with the resnet18_v1 model.  However I get the same error message if I try to use vgg16.
Thank you.
