### ISSUE TITLE
inconsistent results  of Deploy the Pretrained Model 

### ISSUE THREAD

**Issue by kaishijeng** [dmlc/nnvm#193]
I run "Deploy the Pretrained Model on Raspberry Pi" example on firefly 3399 with 2 usecases below and got different performance results.

Usecase 1:  2.2sec

firefly_imagenet_bench.py on firefly
and 
tvm.exec.rpc_server on firefly

ProfileResult(mean=2.0260262451)

Usecase 2:  

firefly_imagenet_bench.py on a linux PC
and
vm.exec.rpc_server on firefly
ProfileResult(mean=0.14720275942)

Shouldn't both usecases have similar ProfileResult? Why is usecase1 10x slower than Usecase2?

Thanks,

**Comment by tqchen** [comment]
Did you build llvm on firefly? It could be possible that the compilation process interferes the execution, or some difference in terms of LLVM configuration support

**Comment by kaishijeng** [comment]
Yes, I built LLVM on firefly. Shouldn't compilation process be finished
before execution?
Is there a way to verify whether it is due to LLVM configuration? Can I use
parameters/compiled results on a PC and move to firefly and then load them
from a firefly and execute instead of using RPC from a PC to firefly?

Thanks,

**Comment by tqchen** [comment]
of course you can move the library to the target machine and load there manually. RPC is only an easy way of doing so without such manual overhead in the experiment

**Comment by tqchen** [comment]
specifically, you can just copy the files. The ".o" file of the generated library needs to be linked with local gcc on the board, this is done by https://github.com/dmlc/tvm/blob/master/python/tvm/contrib/rpc.py#L40 

You can call gcc manually do do that

**Comment by kaishijeng** [comment]
I find net.o.so in /tmp/ directory of my firefly3399 machine. . Is there a
python code which I can load net.o.so and run it on firefly3399?

Thanks,

**Comment by tqchen** [comment]
See http://nnvm.tvmlang.org/how_to/deploy.html

**Comment by tqchen** [comment]
All you have to do is to change remote.load_mdule to tvm.module.load

**Comment by kaishijeng** [comment]
I follow deploy.html and create a python script to load net.so and execute
it.
I found execution time of using net.so created by a local firefly is about
2 sec, but execution time using net.so created by a PC is about 0.2 sec.
I use the same target to create net.so on a PC and firefly and not sure why
the speed is so different

Thanks,
