### ISSUE TITLE
Question about ColorNodeGroup method in graph_algorithm.h

### ISSUE THREAD

**Issue by zhangxiao-ustc** [dmlc/nnvm#201]
In graph_algorithm.h，ColorNodeGroup method is used to color operator nodes in a graph so that nodes in the same color cannot run in parallel. However, if the input param `max_ncolor` is not huge enough, is it possible that nodes in the last color group would run in parallel，or is there any method to prevent this case but I missed？

code used to color all rest nodes with final color：
```
  // assign i for rest of the node
  for (uint32_t i = 0; i < graph.num_nodes(); ++i) {
    if (color->at(i) == max_ncolor) {
      color->at(i) = cindex;
    }
  }
```

**Comment by tqchen** [comment]
The nodes in the same color group have to run serially

**Comment by zhangxiao-ustc** [comment]
This is the conclusion, not the reason. The key question is how to guarantee nodes in the last color group will run serially. I'm still puzzled.

**Comment by tqchen** [comment]
this is an requirement for the runtime to do so, and not directly handled by the coloring algorithm

**Comment by zhangxiao-ustc** [comment]
Ok, I find it. The NDArray instances that share storage own the same VarHandle. So the ’max_ncolor‘ makes a trade-off between storage and parallelism.
It may cost me much time without your reply. Thank you so much.
