### ISSUE TITLE
SoftmaxOutput is not supported in nnvm

### ISSUE THREAD

**Issue by kaishijeng** [dmlc/nnvm#205]
I download resnet-34-0000.params and resnet-34-symbol.json from 
http://data.mxnet.io/models/imagenet/resnet/34-layers/

However, I got an error when I use the following commands to load tme into nnvm:
mx_sym, args, auxs = mx.model.load_checkpoint('resnet-34', 0)
nnvm_sym, nnvm_params = nnvm.frontend.from_mxnet(mx_sym, args, auxs)

  File "/usr/local/lib/python2.7/dist-packages/nnvm-0.8.0-py2.7.egg/nnvm/frontend/mxnet.py", line 341, in from_mxnet
    sym = _from_mxnet_impl(symbol, {})
  File "/usr/local/lib/python2.7/dist-packages/nnvm-0.8.0-py2.7.egg/nnvm/frontend/mxnet.py", line 306, in _from_mxnet_impl
    node = _convert_symbol(op_name, childs, attr)
  File "/usr/local/lib/python2.7/dist-packages/nnvm-0.8.0-py2.7.egg/nnvm/frontend/mxnet.py", line 262, in _convert_symbol
    _raise_not_supported('Operator: ' + op_name)
  File "/usr/local/lib/python2.7/dist-packages/nnvm-0.8.0-py2.7.egg/nnvm/frontend/mxnet.py", line 24, in _raise_not_supported
    raise NotImplementedError(err)
NotImplementedError: Operator: SoftmaxOutput is not supported in nnvm.

**Comment by tqchen** [comment]
cc @zhreshold  We might need a customized transformer here? As softmaxOutput takes second label field which need to be discarded for now

**Comment by PENGUINLIONG** [comment]
@tqchen Maybe it can be made optional?

**Comment by tqchen** [comment]
for now we can just translate it into softmax

**Comment by zt706** [comment]
Hi:
    I want to convert the detection model, you can give suggestions?

eg:
File "/home/zhouji/external_libs/nnvm/python/nnvm/frontend/mxnet.py", line 307, in _from_mxnet_impl
    node = _convert_symbol(op_name, childs, attr, identity_list=['_contrib_MultiBoxPrior', 'transpose'])
  File "/home/zhouji/external_libs/nnvm/python/nnvm/frontend/mxnet.py", line 257, in _convert_symbol
    op = _get_nnvm_op(op_name)
  File "/home/zhouji/external_libs/nnvm/python/nnvm/frontend/mxnet.py", line 11, in _get_nnvm_op
    op = getattr(_sym, op_name)
AttributeError: 'module' object has no attribute '_contrib_MultiBoxPrior'

**Comment by zhreshold** [comment]
@kaishijeng Fixed in #207 
@zt706 The SSD operators are not supported in TVM yet.

**Comment by kaishijeng** [comment]
It compiled and runs. But result is wrong.
See below is my code:
.
[19:32:20] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
('TVM prediction top-1:', 728, 'plastic bag')

It should be tabby cat as described in the tutorial.

('TVM prediction top-1:', 281, 'tabby, tabby cat')


My code:


# coding: utf-8
import mxnet as mx
import nnvm
import tvm
import numpy as np

from mxnet.gluon.model_zoo.vision import get_model
from mxnet.gluon.utils import download
from PIL import Image
from matplotlib import pyplot as plt
import nnvm.compiler
img_name = 'cat.jpg'
synset_url = ''.join(['https://gist.githubusercontent.com/zhreshold/',
                      '4d0b62f3d01426887599d4f7ede23ee5/raw/',
                      '596b27d23537e5a1b5751d2b0481ef172f58b539/',
                      'imagenet1000_clsid_to_human.txt'])
synset_name = 'synset.txt'
#download('
https://github.com/dmlc/mxnet.js/blob/master/data/cat.png?raw=true',
img_name)
#download(synset_url, synset_name)
with open(synset_name) as f:
    synset = eval(f.read())
image = Image.open(img_name).resize((224, 224))
plt.imshow(image)
plt.show()

def transform_image(image):
    image = np.array(image) - np.array([123., 117., 104.])
    image /= np.array([58.395, 57.12, 57.375])
    image = image.transpose((2, 0, 1))
    image = image[np.newaxis, :]
    return image

x = transform_image(image)
print('x', x.shape)

mx_sym, args, auxs = mx.model.load_checkpoint('resnet18_v1', 0)
#mx_sym, args, auxs = mx.model.load_checkpoint('squeezenet_v1.1', 0)
#mx_sym, args, auxs = mx.model.load_checkpoint('resnet-34', 0)
#mx_sym, args, auxs = mx.model.load_checkpoint('ssd_inceptionv3_512', 0)
# now we use the same API to get NNVM compatible symbol
nnvm_sym, nnvm_params = nnvm.frontend.from_mxnet(mx_sym, args, auxs)
#nnvm_sym = nnvm.sym.softmax(nnvm_sym)
target = 'llvm'
shape_dict = {'data': x.shape}
graph, lib, params = nnvm.compiler.build(nnvm_sym, target, shape_dict,
params=nnvm_params)

from tvm.contrib import graph_runtime
ctx = tvm.cpu()
dtype = 'float32'
m = graph_runtime.create(graph, lib, ctx)
m.set_input('data', tvm.nd.array(x.astype(dtype)))
m.set_input(**params)
m.run()
tvm_output = m.get_output(0, tvm.nd.empty((1000,), dtype))
top1 = np.argmax(tvm_output.asnumpy())
print('TVM prediction top-1:', top1, synset[top1])
mx_sym, args, auxs = mx.model.load_checkpoint('resnet18_v1', 0)
nnvm_sym, nnvm_params = nnvm.frontend.from_mxnet(mx_sym, args, auxs)

**Comment by zhreshold** [comment]
Try remove normalization in preprosessing.
  

  
  

  
  
>

**Comment by kaishijeng** [comment]
It works correctly after removing normalization. Any idea when SSD operator
will be available?
Any other object detection model which can be supported by current code?

Thanks,
