### ISSUE TITLE
How to reproduce performance in nnvm announcement  

### ISSUE THREAD

**Issue by xqdan** [dmlc/nnvm#206]
@Huyuwei @Laurawly 
I 'm trying to reproduce performance comparison between mxnet+cudnn vs nnvm+tvm. this first benchmark I'm working on is resnet18.
I've ran thru nnvm+tvm version. I'm trying to run the mxnet version. aligning the benchmark would be very important. 
So what I wanna know is which resnet18 version of mxnet do you use, and how to run with it?  
PS. giving me details as much as possible would be helpful, like specific file/link, etc. 

Thanks!

**Comment by Huyuwei** [comment]
The nnvm benchmark script is https://github.com/dmlc/nnvm/blob/master/examples/benchmark/gpu_imagenet_bench.py

The mxnet benchmark script is 
https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/benchmark_score.py
You may need modify some lines.

Both nnvm and mxnet are using the same resnet symbol file: https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/symbols/resnet.py

**Comment by xqdan** [comment]
great, thanks, @Huyuwei

**Comment by xqdan** [comment]
@Huyuwei please help to confirm what I got, mxnet+cudnn is better than nnvm+tvm, which's not expected.

# nnvm+tvm: 
```
~/nnvm/examples/benchmark$ python3 gpu_imagenet_bench.py --model=resnet --target=cuda --opt-level=3
benchmark args: Namespace(model='resnet', num_iter=1000, opt_level=3, repeat=1, target='cuda')
ProfileResult(mean=**0.01115128139**)
```
# mxnet+cudnn
```
~/mxnet/example/image-classification$ python benchmark_score.py
INFO:root:network: resnet-18
INFO:root:device: gpu(0)
/usr/local/lib/python2.7/dist-packages/mxnet/module/base_module.py:65: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[16:55:57] src/engine/engine.cc:54: MXNet start using engine: NaiveEngine
[16:55:59] src/operator/././cudnn_algoreg-inl.h:106: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
**0.0090970993042**
[16:56:00] src/engine/naive_engine.cc:55: Engine shutdown
```
# what I modify in benchmark_score.py

```
--- a/example/image-classification/benchmark_score.py
+++ b/example/image-classification/benchmark_score.py
@@ -28,7 +28,8 @@ import numpy as np
 logging.basicConfig(level=logging.DEBUG)

 def get_symbol(network, batch_size):
-    image_shape = (3,299,299) if network == 'inception-v3' else (3,224,224)
+    #image_shape = (3,299,299) if network == 'inception-v3' else (3,224,224)
+    image_shape = (3,244,244)
     num_layers = 0
     if 'resnet' in network:
         num_layers = int(network.split('-')[1])
@@ -62,20 +63,22 @@ def score(network, dev, batch_size, num_batches):
             output.wait_to_read()

     # return num images per second
+    print(time.time() - tic)
     return num_batches*batch_size/(time.time() - tic)

 if __name__ == '__main__':
-    networks = ['alexnet', 'vgg', 'inception-bn', 'inception-v3', 'resnet-50', 'resnet-152']
+    #networks = ['alexnet', 'vgg', 'inception-bn', 'inception-v3', 'resnet-50', 'resnet-152']
+    networks = ['resnet-18']
     devs = [mx.gpu(0)] if len(get_gpus()) > 0 else []
     # Enable USE_MKL2017_EXPERIMENTAL for better CPU performance
-    devs.append(mx.cpu())
+    #devs.append(mx.cpu())

-    batch_sizes = [1, 2, 4, 8, 16, 32]
+    batch_sizes = [1]

     for net in networks:
         logging.info('network: %s', net)
         for d in devs:
             logging.info('device: %s', d)
             for b in batch_sizes:
-                speed = score(network=net, dev=d, batch_size=b, num_batches=10)
-                logging.info('batch size %2d, image/sec: %f', b, speed)
+                speed = score(network=net, dev=d, batch_size=b, num_batches=1)
+                #logging.info('batch size %2d, image/sec: %f', b, speed)
```
# and my env info:

----------Python Info----------
('Version :', '2.7.6')
('Compiler :', 'GCC 4.8.4')
('Build :', ('default', 'Oct 26 2016 20:30:19'))
('Arch :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version :', '9.0.1')
('Directory :', '/usr/local/lib/python2.7/dist-packages/pip')
----------MXNet Info-----------
('Version :', '0.11.0')
('Directory :', '/usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet')
Traceback (most recent call last):
File "check.py", line 108, in check_mxnet
with open(commit_hash, 'r') as f:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/mxnet-0.11.0-py2.7.egg/mxnet/COMMIT_HASH'

----------System Info----------
('Platform :', 'Linux-4.2.0-27-generic-x86_64-with-Ubuntu-14.04-trusty')
('system :', 'Linux')
('node :', 'ubuntu')
('release :', '4.2.0-27-generic')
('version :', '#32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016')
----------Hardware Info----------
('machine :', 'x86_64')
('processor :', 'x86_64')
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 72
On-line CPU(s) list: 0-71
Thread(s) per core: 2
Core(s) per socket: 18
Socket(s): 2
NUMA node(s): 2
Vendor ID: GenuineIntel
CPU family: 6
Model: 63
Stepping: 2
CPU MHz: 2300.000
BogoMIPS: 4592.04
Virtualization: VT-x
L1d cache: 32K
L1i cache: 32K
L2 cache: 256K
L3 cache: 46080K
NUMA node0 CPU(s): 0-17,36-53
NUMA node1 CPU(s): 18-35,54-71
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.1997 sec, LOAD: 2.2869 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.1393 sec, LOAD: 0.5727 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.2254 sec, LOAD: 1.0769 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.3398 sec, LOAD: 0.3019 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.1826 sec, LOAD: 0.7265 sec.
Error open Gluon Tutorial(cn): https://zh.gluon.ai, <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>, DNS finished in 1.04916906357 sec.

**Comment by Huyuwei** [comment]
@xqdan The result is reasonable, on my machine with GTX1080 nnvm/tvm is also slightly slower than mxnet. The schedules for resnet workloads (mainly 3x3 conv) are specifically optimized for K80, and performance drop on other platforms is expected.

You may try mobilenet, nnvm should be faster than mxnet :)

**Comment by xqdan** [comment]
ok, my gpu is k40.
I'll try mobilenet.

Thanks!

**Comment by xqdan** [comment]
BTW, where can I get mxnet version mobilenet?

**Comment by xqdan** [comment]
0.00467205047607 mxnet
0.005099601167 nnvm

still worse than mxnet

**Comment by Huyuwei** [comment]
Well, on GTX1080 it is:
0.00183 mxnet
0.00171 nnvm

We can expect better performance after fine tuning TVM schedules for a specific hardware platform.

**Comment by xqdan** [comment]
any advice for fine tuning?

**Comment by Huyuwei** [comment]
https://github.com/dmlc/tvm/issues/423 I think auto tuner is in progress.

You can modify parameters like num_thread_y, num_thread_x, blocking_h, blocking_w, to see their effects, and to tune these parameters for better performance. This [tutorial](http://tvmlang.org/2017/08/22/Optimize-Deep-Learning-GPU-Operators-with-TVM-A-Depthwise-Convolution-Example.html) may help, see the part of *Tuning Parameters of Thread Numbers*.

**Comment by xqdan** [comment]
thanks, after tuning, nnvm is ProfileResult(mean=0.004521885976), better than mxnet

**Comment by Laurawly** [comment]
@xqdan Just wondering if you've turned on llvm-config for tvm which is needed for opt-level=2. It usually gives some performance boost.

**Comment by xqdan** [comment]
do you mean this, yes 

```
# whether build with LLVM support
# Requires LLVM version >= 4.0
# Set LLVM_CONFIG to your version, uncomment to build with llvm support
#
LLVM_CONFIG = ~/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04/bin/llvm-config
```

**Comment by xqdan** [comment]
@Laurawly what's the magic from llvm-config?

**Comment by Laurawly** [comment]
@xqdan NVM, I find that using --opt-level=2 needs llvm-config turned on.  I was actually thinking about using nvcc to compile the code but noticed that it's already there in the benchmark code.
