### ISSUE TITLE
Deploy a model on an arm devices

### ISSUE THREAD

**Issue by BingzheWu** [dmlc/nnvm#208]
In the tutorial, there is an example to show how to deploy a graph on a Raspberry Pi, but the tool used is the RPC. I want to know if I can do inference without my local machine, more specifically, how can I use the compiled graph on an arm device without my local PC?

**Comment by ZihengJiang** [comment]
Deployment requires three things:
- graph json file
- compiled lib
- parameter blob

which can be generated by `nnvm.compiler.build`. If you have those files on your arm device, you can deploy the model as the [document](http://nnvm.tvmlang.org/how_to/deploy.html), whether you upload them by rpc, copy them by external storage or compile the graph in place. Hope I made it clear:)

**Comment by BingzheWu** [comment]
Hi, ZHiheng, I mean how can I use the compiled lib in the device, all example in the document is to use a python script and tvm to use the complied graph, but if there is a c code example?

**Comment by WolffyChen** [comment]
I have run successfully on the Hi3519A board, although it is slower than MXNet(I am checking it). Here are some reference steps.

- Use "nnvm.compiler.build" in python to generate three things as @ZihengJiang mentioned. To create the "net.o" file used for Hi3519A, I set the compile target to "**llvm --system-lib -target=armv7l-hisiv600-linux-gnueabi -mcpu=cortex-a17 -mfloat-abi=soft -mattr=+neon**". You can change to your own target option.

- Write your c++ deploy code with the reference of [document](http://nnvm.tvmlang.org/how_to/deploy.html). And you should use "**tvm::runtime::Module mod_syslib = (*tvm::runtime::Registry::Get("module._GetSystemLib"))();**" to get module from "net.o" while the original reference code from "deploy.so".

- Then you can compile it as the [document](http://docs.tvmlang.org/how_to/deploy.html) and [Makefile](https://github.com/dmlc/tvm/blob/master/apps/howto_deploy/Makefile). If you want to use pre-built libtvm_runtime.so, please build the runtime library with your cross-compiler first with the reference of [document](http://docs.tvmlang.org/tutorials/deployment/cross_compilation_and_rpc.html#sphx-glr-tutorials-deployment-cross-compilation-and-rpc-py).

**Comment by tqchen** [comment]
you could try to use
```
target = tvm.target.rasp("--system-lib -target=armv7l-hisiv600-linux-gnueabi -mcpu=cortex-a17 -mfloat-abi=soft -mattr=+neon")
```
so it triggers the raspberry pi devices. You can use the rpc to test the speed then confirm with the C++ deployment code

**Comment by WolffyChen** [comment]
When I try to use "tvm.target.rasp(...)" to compile my model, the error occurred as #224 show.
