### ISSUE TITLE
Some troubles on deploying model on Raspberry Pi 

### ISSUE THREAD

**Issue by BingzheWu** [dmlc/nnvm#209]
I have followed all instructions to install the nnvm and tvm. And I have tried the example in [http://nnvm.tvmlang.org/tutorials/deploy_model_on_rasp.html#sphx-glr-tutorials-deploy-model-on-rasp-py](url) to deploy the resnet model on Rpi. But when I run the compile code, the error happened. The log is
`
NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/home/bingzhe/project/dmlc/nnvm/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/bingzhe/project/dmlc/nnvm/python/nnvm/top/nn.py", line 140, in compute_max_pool2d
    pool_type='max', ceil_mode=ceil_mode)
TypeError: pool() got an unexpected keyword argument 'ceil_mode'
`
I have checked the python code of nn.py in topi , there is a keyword 'ceil_mode', so i don't how to fix it. Can any one help me?

**Comment by tqchen** [comment]
please update the tvm/topi installation. Possibly by reinstall the topi or set the correct path

**Comment by BingzheWu** [comment]
Yes, I have updated the source code and reinstall it. But it still didn't work. I have tried to use the topi.nn.pool in ipython, I have checked the function have the ceil_mode keywords. But I don't know what's wrong with the example script

**Comment by BingzheWu** [comment]
I have restared the juypter notebook, it works. Thak you all guys.
