### ISSUE TITLE
What does NNVM feed to TVM? Halide IR, or schedule+alg?

### ISSUE THREAD

**Issue by derisavi** [dmlc/nnvm#210]
Hi,
I'm wondering whether NNVM feeds TVM with Halide IR or whether it gives TVM algorithm + schedule for TVM to convert to Halide IR, or maybe something else.
Whenever there is a auto-scheduler for TVM (assuming it will be something similar to Halide's), will the auto-scheduler be used (i.e., perform any code transformations) when TVM if fed by NNVM? Will the transformations be distinct from the transformations that NNVM does?

**Comment by derisavi** [comment]
My understanding is that topi provides optimized schedules for a number of common "operators" (matmul, conv, etc.) on a number of hardware architectures. 
Do you mean that NNVM is calling those operators and that's how the alg+schedule is provided? If yes, what schedule is used if there is no topi operator matched to the computation represented in NNVM?

**Comment by tqchen** [comment]
The idea would be add that to topi, this encourages more reuse and unittesting.  Note that topi allows operator composition easily so current list of core operators already covers most core usecases.

See current list of supported operators [here](http://nnvm.tvmlang.org/top.html)  and source code [here](https://github.com/dmlc/nnvm/tree/master/python/nnvm/top)

**Comment by xqdan** [comment]
is it possible we make a schedule on graph automatically and then lower alg+schedule into tvm IR? in this way, IR describes everything from graph, no need the concept 'operator' any more, also we get more performance benefits, because schedule on graph has the entire view of networks.

**Comment by tqchen** [comment]
That is what the graph partition and fuse pass do

**Comment by xqdan** [comment]
I see what you mean, but we only fuse to what we have in tvm rather than anything described in tvm IR, no need add op in topi. fusing to anything in IR, that might be the way to go.

**Comment by tqchen** [comment]
Topi is only a convenient way to construct the tvm descriptions and there is no obstacle on preventing adding ops directly to nnvm. But I do think making topi cover more ops is more principled and reusable
