### ISSUE TITLE
How to handle additional operators from ONNX / MXNet?

### ISSUE THREAD

**Issue by imai-lm** [dmlc/nnvm#211]
Recently, ONNX team is proposing some way of private extensions to additional operators. (See [here](https://github.com/onnx/onnx/pull/175/commits/ab7fff23ed2a998eccfc423c164d1cad2b4271dd#diff-1150153cdbc4a013967849d24332aa10R155).) 
Plus, of course MXNet has ability to append new operators [in this way](https://mxnet.incubator.apache.org/how_to/new_op.html).

I'd like to handle these operators in NNVM, even if it doesn't support them officially. Is there any good way to do this?
My proposal is to extend `nnvm.frontend.from_onnx()` and `nnvm.frontend.from_mxnet()` and set some user-extensible hooks inside, in which users can append additional conversion/registration of operators to NNVM.

**Comment by tqchen** [comment]
This sounds good. For nnvm support itself, we can simply add new operators by registering it to NNVM and register the compute/schedule functions in python side.

On the other hand, if the operator is reasonable, we will be very welcoming to add them, first mayb to contrib and then make them official

**Comment by PENGUINLIONG** [comment]
(FYI) NNVM register all the operators in [a relatively extensible way](https://github.com/dmlc/nnvm/blob/master/python/nnvm/top/transform.py#L11-L18). So it won't be too hard to extend the operator set through Python API.

**Comment by imai-lm** [comment]
Thanks. I will try it from tomorrow since I'm a bit busy today.

**Comment by xqdan** [comment]
notice that there are lots of ops in mxnet, which nnvm don't support right now, can we port and reuse them in nnvm?

**Comment by tqchen** [comment]
more operators are always welcomed as long as we add them in a formal way via topi

**Comment by xqdan** [comment]
Actually I mean can we just move like "mxnet/src/operator/loss_binary_op.cu" into nnvm/tvm， does nnvm/tvm support this?

**Comment by tqchen** [comment]
well, this is supported as external kernel, but less encouraged as it is not portable across backends, for most of them it is likely just as easy to write topi description plus a simple  schedule

**Comment by bonotake** [comment]
Hmm, it is more difficult to make a test code, than to implement itself... Any idea is welcome.
(This is another account of @imai-lm, sorry for confusing.)
