### ISSUE TITLE
Why nnvm::Node does not have output nodes?

### ISSUE THREAD

**Issue by yehenrytian** [dmlc/nnvm#212]
This is more of a question rather than an issue. I am looking at the definition of nnvm:Node in node.h:
```
class Node {
 public:
  /* \brief The attributes in the node. */
  NodeAttrs attrs;
  /*! \brief inputs to this node */
  std::vector<NodeEntry> inputs;
  /*!
   * \brief Optional control flow dependencies
   *  Gives operation must be performed before this operation.
   */
  std::vector<NodePtr> control_deps;
......
```
I am wondering why you don't have output Nodes for each of your graph nodes? Since it looks like your graph does not have `Edge` either (as like the Graph in TensorFlow). Can anyone explain how this works? Thanks!

**Comment by PENGUINLIONG** [comment]
This is how I see: Note that [`NodeEntry`](https://github.com/dmlc/nnvm/blob/master/include/nnvm/node.h#L29-L42) contains a `NodePtr`, and `NodePtr` in NNVM is a [`shared_ptr`](https://github.com/dmlc/nnvm/blob/master/include/nnvm/node.h#L27), i.e., it's reference counted. If output is also placed in `Node`, the reference goes both directions. Then the `Node` objects will not be released properly. Although we have `weak_ptr` that allow us to refer to `Node`s without increment of reference count, it involves more complicated management of resources. So for simplicity, it's not used.

Also, the symbol `NodePtr` is defined to allow future adjustment of implementation of it. Maybe someday it no longer is a `shared_ptr`. So we cannot rely on `shared_ptr`-only features too much, we simply consider it as a reference.

**Comment by yehenrytian** [comment]
@PENGUINLIONG Thanks for the reply. From memory management point of view, your answer makes sense. Maybe I am thinking too much about the TensorFlow data flow graph, but after more thinking I am a bit confused now, I don't really understand why for the TF data flow graph we need edges and also the index of src/dst for each edge...

**Comment by PENGUINLIONG** [comment]
It's pretty common that in architecture design period people come up with an idea then find it troublesome a couple of months later. Maybe graph edge is not the best design over all, but when they decided to use it, it just prevailed. Then versions are released, they can't simply abandon it for compatibility concerns.
