### ISSUE TITLE
[LANG]  C++  Compiler API

### ISSUE THREAD

**Issue by MoritzMaxeiner** [dmlc/nnvm#213]
Hi, since I couldn't find an example on how to do this (or if it can be done at all with nnvm) I have to ask:
Suppose I've already trained a model with some ML library/framework for which nnvm has import support , so I have a computational graph in e.g. ONNX or MXNet format.
After I've loaded this in python nnvm into a `sym, params` pair, can I
- export that pair to files
- load those files into a C++ application (via nnvm's C++ API)
- compile&run that graph in said C++ application (via nnvm's C++ API), do to inference for the trained model.

**Comment by tqchen** [comment]
In the current state, you  compile the graph in python, and save the lib, graph, params,  pair and deploy that via C++ (using only tvm runtime API)

**Comment by tqchen** [comment]
related questions in here https://github.com/dmlc/tvm/issues/600

See also http://nnvm.tvmlang.org/how_to/deploy.html  and http://docs.tvmlang.org/how_to/deploy.html

**Comment by MoritzMaxeiner** [comment]
Thank you for the information, I've read the examples and tutorials, but AFAICT they don't cover my use case:
Compiling in python means the C++ application receives platform dependent object code (the library) as input. My use case requires the input for the C++ application to be platform agnostic.
I can understand if covering such use cases is not a design goal of nnvm, but I wanted to ask first to make sure.

**Comment by tqchen** [comment]
I see what you mean. It is possible, as both nnvm and tvm are cxx project by nature and all the optimization pass are in cxx. 

Doing so means improve  the topi schedule and declaration support in cxx. We have some of them and it is not hard to migrate some further.

This will mean some engineering overhead but the cost should be minimum as the python part serves as good reference 

The only reason python is used here is to be able to build up the schedule quickly and there is no obstacle on moving things toward pure cxx. 

Contribution is welcomed here

**Comment by tqchen** [comment]
Here are the relevant code

- The python side registry https://github.com/dmlc/nnvm/blob/master/python/nnvm/top/nn.py#L38
- The c++ side of registration https://github.com/dmlc/nnvm/blob/master/src/compiler/packed_func_ext.cc#L88

Note that these python code are passed as c++ callbacks before being registered to the registry. So in order to support what you want, we just need to implement these python logics in c++ and directly register in c++ side. The only reason python is used so far is for quick improvement of the project

**Comment by MoritzMaxeiner** [comment]
Okay, thank you for the comprehensive answer and the confirmation that this feature request does not go against nnvm's design goals.
I'm not sure if I currently have enough time to implement this myself (as I don't know enough about nnvm's architecture as of yet to judge the amount of work necessary), but I'll have a look when I can.
Regardless of that, I'll leave the issue open as a feature request, unless you object.

**Comment by samhodge** [comment]
I will have this use case also, so I am watching the development here, I am not sure if my skills are up to the task to contribute.

**Comment by tqchen** [comment]
move to #343
