### ISSUE TITLE
[OP] Support conv2d_transpose in nnvm compiler

### ISSUE THREAD

**Issue by tqchen** [dmlc/nnvm#214]
Already supported in topi, need to update nnvm compiler @Huyuwei

**Comment by Huyuwei** [comment]
#217

**Comment by tqchen** [comment]
Awesome!

**Comment by tqchen** [comment]
cc @masahi

**Comment by masahi** [comment]
@Huyuwei Great! Was waiting for this. Will try importing DCGAN and other image-out models.
