### ISSUE TITLE
how to call cuda op in nnvm/tvm?

### ISSUE THREAD

**Issue by xqdan** [dmlc/nnvm#215]
is there an example for this path?

best

**Comment by tqchen** [comment]
can you be more specific on what do you mean? is it about calling a cudnn operator or a hand crafted cuda code?

**Comment by tqchen** [comment]
Most of external things can be wrapped as extern ops. http://docs.tvmlang.org/tutorials/language/extern_op.html#sphx-glr-tutorials-language-extern-op-py

**Comment by xqdan** [comment]
@tqchen yes, we have hand crafted cuda code.

**Comment by tqchen** [comment]
So it is likely that extern mode is your answer for now. If you are interested in study the device calling mode of CUDAModule, we might be able to also find some other rtc like alternatives.
