### ISSUE TITLE
Is output net as nnvm.compiler.build() method returned a optimized graph?

### ISSUE THREAD

**Issue by BigJerry** [dmlc/nnvm#221]
As title said, does nnvm.compiler.build() method return the final optimized graph for tvm to use? Any further optimization could be done after it?

**Comment by tqchen** [comment]
build returns an optimized graph that is already lowered to tvm functions, so no further optimizations can be done. To do intermediate optimizations, use tvm.compiler.optimize or look into the logic tvm.compiler.build

**Comment by BigJerry** [comment]
So the normal workflow is gonna like this: firstly, in NNVM part ,utilizing nnvm.compiler.build( ) to obtain an optimized graph . And then, at TVM side , we generate runtime code using tvm.contrib.graph_runtime.create( ). Am I right?

**Comment by tqchen** [comment]
Runtime code is already generated in build, and graph runtime create is only creating a wrapper around that

**Comment by BigJerry** [comment]
ok, got it
