### ISSUE TITLE
Why use nnvm much slower than MXNet on the Hi3519A board?

### ISSUE THREAD

**Issue by WolffyChen** [dmlc/nnvm#224]
Hi all,

I have run my model successfully on the Hi3519A board, but it is slower than MXNet. I do it as follows.

- To create the "net.o" file used for Hi3519A, I set the compile target to "**llvm --system-lib -target=armv7l-none-linux-gnueabi -mcpu=cortex-a17 -mfloat-abi=soft -mattr=+neon**".

- I use "**tvm::runtime::Module mod_syslib = (*tvm::runtime::Registry::Get("module._GetSystemLib"))();**" to get module from "net.o".

- Then I deploy it using both the "**all in one TVM package library**" and "**pre-built libtvm_runtime.so(build with openblas)**".

The cost of the "**all in one TVM package library**" is _441ms_ while "**pre-built libtvm_runtime.so**" is _600ms_. But when I use MXNet, it only cost _181ms_. Why is the model running on nnvm much slower than MXNet? Is there any wrong with my usage?

The compile option of MXNet library and OpenBLAS library on Hi3519A is "**-mfloat-abi=softfp -mfpu=neon -mcpu=cortex-a17.cortex-a7**". But in nnvm's target, I can only set it to "**-mcpu=cortex-a17 -mfloat-abi=soft -mattr=+neon**". Does this have any effect on it?

Thank you very much!
Hope Reply.

**Comment by ZihengJiang** [comment]
Currently, there is only specific schedule for Raspberry Pi, and we pick the schedule by the target. So if you change the compilation target, it would pick the naive schedule which leads to the slow speed.

Do you have any suggestion? @tqchen

**Comment by tqchen** [comment]
For now a quick way to resolve this issue is simply use tvm.rasp(target_string)

**Comment by tqchen** [comment]
Another way to solve this is to register also rasp schedule as arm schedule, and allow fallback to this when the specific target is not available. This happens for GPU based schedules

**Comment by WolffyChen** [comment]
That is to say currently only Raspberry Pi is optimized on arm cpu. And when I try to use "tvm.target.rasp()" to compile my model, the following error occurred: 
`ValueError: no schedule for such workload: Workload(height=216, width=384, in_filter=3, out_filter=8, hkernel=3, wkernel=3, hpad=1, wpad=1, hstride=2, wstride=2)`
This means some operations are not supported yet?

**Comment by austingg** [comment]
@WolffyChen , currently only schedule for specific Workload, such as Mobilenet1.0 or Resnet's  conv specifications.

**Comment by WolffyChen** [comment]
Thank you.

**Comment by wjtan99** [comment]
@WolffyChen What network model did you test on Hi3519?  Did you use the IVE?  
Thanks a lot.

**Comment by WolffyChen** [comment]
Mobilenet1.0 after cutting. Do not use IVE, just CPU.

**Comment by wjtan99** [comment]
I am also learning Hi3519 programming and optimization.  Can you give me some advice?  Can you email me at wjtan99@hotmail.com?  Thanks.

**Comment by WolffyChen** [comment]
I know little about Hi3519, just use its CPU to run the program with cross compile.

**Comment by wjtan99** [comment]
which Moblienet with cutting, Do you have a link to the source?  And what is your command to cross compile for Hi3519?  Thanks.
