### ISSUE TITLE
[BACKEND] Support for NCNN backend.

### ISSUE THREAD

**Issue by PENGUINLIONG** [dmlc/nnvm#229]
[NCNN](https://github.com/Tencent/ncnn) is a multi-platform, high-performance back-end for mobile devices. It's been actively updated and is backed by Tencent. Any interest to provide support for NCNN?

**Comment by tqchen** [comment]
Nnvm compiler mainly aims to do automatic compilation with graph optimization, this being said, it is interesting to look into the optimization being done at NCNN and see if we can bring some of them into the topi
