### ISSUE TITLE
nnvm build failed with multiple outputs net

### ISSUE THREAD

**Issue by xqdan** [dmlc/nnvm#236]
hi all,
   seems that nnvm doesn't consider multiple outputs nets for now, please confirm, and how to fix this?
   
   see code below, after gets nnvm_sym with a symbol group from mxnet, nnvm.compiler.build will fail.
   when prints mx_sym, says 
`<Symbol group [bbox_pred, cls_prob, proposal, proposal]>`
   when prints nnvm_sym, says
` [<nnvm.symbol.Symbol object at 0x7f68f37a6168>, <nnvm.symbol.Symbol object at 0x7f68f37a6c58>, <nnvm.symbol.Symbol object at 0x7f68fb013948>, <nnvm.symbol.Symbol object at 0x7f68fb013948>]`

  Traceback i got, seems that nnvm.compiler.build doesn't consider sym list right now, which is supported in nnvm c++ version.
  
```
  Traceback (most recent call last):
  File "pavnet.py", line 36, in <module>
    graph, lib, params = nnvm.compiler.build(nnvm_sym, target, shape_dict, params=nnvm_params)
  File "/home/danxiaoqiang/nnvm/python/nnvm/compiler/build_module.py", line 213, in build
    graph = graph if isinstance(graph, _graph.Graph) else _graph.create(graph)
  File "/home/danxiaoqiang/nnvm/python/nnvm/graph.py", line 272, in create
    symbol.handle, ctypes.byref(ghandle)))
AttributeError: 'list' object has no attribute 'handle'
```

the related code:
```
# for a normal mxnet model, we start from here
mx_sym, args, auxs = mx.model.load_checkpoint('pvanet', 0)
# now we use the same API to get NNVM compatible symbol
print(mx_sym)
nnvm_sym, nnvm_params = nnvm.frontend.from_mxnet(mx_sym, args, auxs)

# now compile the graph
import nnvm.compiler
target = 'cuda'
shape_dict = {'data': x.shape}
with nnvm.compiler.build_config(opt_level=3):
     graph, lib, params = nnvm.compiler.build(nnvm_sym, target, shape_dict, params=nnvm_params)
```

**Comment by ZihengJiang** [comment]
https://github.com/dmlc/nnvm/pull/247

I guess this PR would fix this, could you help me test it since I do not have the checkpoint file of your reproduce code.

**Comment by xqdan** [comment]
problem solved. thanks for fixing.
