### ISSUE TITLE
NNVM Deployment on C++

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/nnvm#237]
Hi All,

I just started with NNVM and TVM from past week, now ran into below issue.

NNVM produce a graph(json), module (lib) and params which can be imported into any language as in example get_started.py.

`fcreate = tvm.get_global_func("tvm.graph_runtime.create")`
`ctx = tvm.gpu(0)`
`gmodule = fcreate(loaded_json, loaded_lib, ctx.device_type, ctx.device_id)`
`set_input, get_output, run = gmodule["set_input"], gmodule["get_output"], gmodule["run"]`
`set_input("x", tvm.nd.array(x_np))`
`gmodule["load_params"](loaded_params)`
`run()`
`out = tvm.nd.empty(shape)`
`get_output(0, out)`
`print(out.asnumpy())`

To use it with native C++ I couldn't find corresponding API @ http://docs.tvmlang.org/doxygen/namespaces.html

Also I referred from TVM howto examples library preparation and it has an entry function definition which is accessed as function pointer to call the module function.

`# Compile library as dynamic library`
`fadd_dylib = tvm.build(s, [A, B], "llvm", name="addone")`
`dylib_path = os.path.join(base_path, "test_addone_dll.so")`
`fadd_dylib.export_library(dylib_path)`

I see some difference in the library interfaces in above two cases.
Am I missing something here ?

Regards,
Siva

**Comment by PENGUINLIONG** [comment]
All APIs available are in the namespace `topi`.

BTW, you can make your text more readable by turning them into code blocks.

**Comment by srkreddy1238** [comment]
sorry about the readability, I didn't see it while copy paste.

[topi](http://docs.tvmlang.org/doxygen/namespacetopi.html) has the Tensor API for TVM. 

I am looking for C / C++ API for below python code.

`fcreate = tvm.get_global_func("tvm.graph_runtime.create")`
`ctx = tvm.gpu(0)`
`gmodule = fcreate(loaded_json, loaded_lib, ctx.device_type, ctx.device_id)`
`set_input, get_output, run = gmodule["set_input"], gmodule["get_output"], gmodule["run"]`
`set_input("x", tvm.nd.array(x_np))`
`gmodule["load_params"](loaded_params)`
`run()`
`out = tvm.nd.empty(shape)`
`get_output(0, out)`


Siva

**Comment by PENGUINLIONG** [comment]
Check out these links:

https://github.com/dmlc/nnvm/blob/master/include/nnvm/c_api.h

https://github.com/dmlc/tvm/blob/master/include/tvm/runtime/c_runtime_api.h

**Comment by srkreddy1238** [comment]
Thanks for the info.

Finally I found the sample implementation @ [https://github.com/dmlc/nnvm/blob/master/docs/how_to/deploy.md](https://github.com/dmlc/nnvm/blob/master/docs/how_to/deploy.md)

Siva
