### ISSUE TITLE
Python interface only supports float32

### ISSUE THREAD

**Issue by abergeron** [dmlc/nnvm#248]
I'm not sure if this is a limitation of the underlying code or not, but extending this to other data types is pretty important for us.

If that is not possible (or very hard) we probably will have to look elsewhere.

**Comment by tqchen** [comment]
https://github.com/dmlc/nnvm/blob/master/python/nnvm/compiler/build_module.py#L186 The dtype argument can take in arbitrary data types actually

**Comment by tqchen** [comment]
Alright, I think I am getting ahead of myself. NNVM is designed for supporting arbitrary types and there is already code in a separate branch that does. But it is indeed true that the initial release restrict itself to float32. @ZihengJiang will PR the changes necessary to enable general types.

**Comment by tqchen** [comment]
https://github.com/dmlc/nnvm/issues/248
