### ISSUE TITLE
NotImplementedError: Operator: SoftmaxOutput is not supported in nnvm.

### ISSUE THREAD

**Issue by Vernlium** [dmlc/nnvm#251]
I download resnet-18-0000.params and resnet-18-symbol.json from
http://data.mxnet.io/models/imagenet/resnet/18-layers/

However, I got an error when I use the following commands to load tme into nnvm:
```
mx_sym, args, auxs = mx.model.load_checkpoint('resnet-34', 0)
nnvm_sym, nnvm_params = nnvm.frontend.from_mxnet(mx_sym, args, auxs)
```

I have seen the issue #205. The issue can't answer my doubt.

My question is: 

**How can I load my own mxnet model(include SoftmaxOutput op) to convert to nnvm?**
The mxnet.gluon.model_zoo.vision.get_model just load the given mxnet model.

**Comment by tqchen** [comment]
This should have already been solved by https://github.com/dmlc/nnvm/pull/207  please update your nnvm to latest version in master and retry
