### ISSUE TITLE
Support keras

### ISSUE THREAD

**Issue by Nuka-A** [dmlc/nnvm#253]
Hi,

I'm interested in this project, so i would like to know it more.
I heard that there is a future work to support keras, and its status is in "work in progress" now.

http://www.tvmlang.org/2017/10/06/nnvm-compiler-announcement.html

is there any progress about this work now?
there is no source code and no issues about it, so i'm wondering about the current status.
And developer of keras does not know about this work.

Thanks

**Comment by tqchen** [comment]
#273
