### ISSUE TITLE
Support for the Training

### ISSUE THREAD

**Issue by Nuka-A** [dmlc/nnvm#254]
Hi,

sorry for my continuous posts. I have one more question about this project.

I knew that NNVM can infer with pre-trained model already.
On the other hand, NNVM does not seem to support for the training.

is there any schedule to support for the training?

Thanks

**Comment by tqchen** [comment]
The support for training means support automatic differentiation and run the gradient graph. This pass is already in nnvm, and you can find existing projects like tinyflow and mxnet relies on this to support training.

The current compilation part of the project starts with inference optimization, but the infra can be used to support the training. It is on our list.

**Comment by Nuka-A** [comment]
I looked a bit into "tinyflow".
I could see that there is a backward process.

From my understanding, the implement of the training path is seemed to rely on above software layers (mxnet, tinyflow) now.
Are theses paths will be merged in future?

thanks

**Comment by tqchen** [comment]
There is need of backward pass, instead a gradient pass is needed, which is already in nnvm

**Comment by Nuka-A** [comment]
I got it.

thanks. and I hope future works about this project.
