### ISSUE TITLE
llvm has different result compare with cuda 

### ISSUE THREAD

**Issue by cocorecoco** [dmlc/nnvm#256]
I use coremltools converting my face feature caffe model into coremlmodel， then I use 'llvm' mode as 
```
m =  coremltools.models.MLModel("feature.mlmodel")
graph, params = nnvm.frontend.from_coreml(m)
data_shape=(1, 3, 128,128)
dtype="float32"
data_array = np.zeros(data_shape)
target = "llvm"
graph, lib, params = nnvm.compiler.build(graph, target, {"data":data_shape}, params=params)
module = graph_runtime.create(graph, lib, ctx=tvm.cpu(0))
input = tvm.nd.array(data_array.astype(dtype), ctx=tvm.cpu(0))
output = tvm.nd.empty((1,128), ctx=tvm.cpu(0))
module.set_input(**params)
module.set_input("data", input)
module.run()
module.get_output(0, output) 
print output
```
I got result :
                 `-0.08615206 -0.99575126  1.16580915  0.08832981 -2.24378753  1.07615602
  -0.66468263 -1.3100847  -1.28539765 -1.27316701  0.23277336 -1.8878299
   0.24762222  0.73060477 -0.41107419  1.32575309 -0.2943002  -2.42759585
  -0.71395212  1.82120383 -1.30882645  1.07307076 -2.13105035  1.05349827
   0.02298812 -1.54944086  0.27341911 -3.29777098 -0.34716088  0.60930336
  -0.24868928 -2.17120218  1.01481795 -0.01312418  1.59760427  0.55900514
   1.02230155 -0.03663054  0.55957121 -0.44893131 -1.42476034  1.10719848
   0.65711087 -0.24953988 -1.20152199  0.53164178 -1.39661634 -0.46515021
   0.39015353  1.23380053  0.22646707 -1.09059131 -0.59676206 -0.62703317
  -0.46421224 -1.36989713  0.62499529  1.42504394  0.02863264  0.38509309
  -0.92143816  0.96039677  0.32998624  0.77582961  0.72157913  0.4468345
  -0.27158764  2.75281286  1.22024298 -0.63331604 -0.13923766  0.18169373
  -0.63089353 -0.18605086 -0.81953841 -0.11737    -0.13811073 -0.17918411
  -0.81450355 -0.05226241  0.32725522  0.96296692 -0.33791852 -2.90118265
   1.66815698  0.6774115   1.02525091 -1.60889709 -2.4024539   0.97682995
   1.58931446 -1.4376564  -0.19479544  0.32387602 -3.46545935  0.51604605
   1.40582621  0.08572948 -0.55040336 -3.01527166  1.70315576  0.56325185
  -1.22547662  0.76933736 -0.72310251  0.29625636 -0.50884777 -2.08212757
  -0.1036509  -0.64904988 -1.29078376  1.738168    0.08230036  0.52165502
  -0.63361371 -1.98875463  0.58435404 -0.42561671  0.84983826 -2.00356364
  -0.8385942   0.22991869 -0.69639337  1.43427563  0.71959221  0.01175576
   1.15414417  0.3057999`

but when change to "cuda" mode:
```
m =  coremltools.models.MLModel("feature.mlmodel")
graph, params = nnvm.frontend.from_coreml(m)
data_shape=(1, 3, 128,128)
dtype="float32"
data_array = np.zeros(data_shape)
target = "cuda"
graph, lib, params = nnvm.compiler.build(graph, target, {"data":data_shape}, params=params)
print lib
lib.export_library("mylib.so")

module = graph_runtime.create(graph, lib, ctx=tvm.gpu(0))
input = tvm.nd.array(data_array.astype(dtype), ctx=tvm.gpu(0))
output = tvm.nd.empty((1,128), ctx=tvm.gpu(0))
module.set_input(**params)
module.set_input("data", input)
module.run()
module.get_output(0, output) 
print output
```

I get result: 
`0.47059405 -0.38169408  0.6594258   0.58918369 -0.86561477  0.10290127
   0.10365771 -0.27006361 -0.51356578 -1.35330832  0.24028569 -1.21617365
  -0.04542941  0.76992393  1.49134088  1.31226254 -0.4210532  -1.80403733
   0.08988631  2.17677641 -1.18039107 -0.36840662 -0.71274346  0.49923426
   1.41658437 -1.26614952  0.04356013 -2.28113365 -0.02232735  0.62781763
  -0.29103664 -0.31189185  1.09728456 -0.0321308   0.77184528  1.07987666
   0.02790185  0.88962877  0.50654578 -1.02621853 -0.86890489 -0.11230138
   0.91525906  0.20496422 -0.7703566  -0.1986229  -0.71524465 -0.4387677
  -0.73195469  0.98497462  0.92786729 -0.86619836 -0.93220586 -0.70494908
  -0.86353123 -0.6371305   0.12184864  0.38348106 -0.26842454  0.40882969
  -0.90168089  0.08419222  0.07722323  0.37939939  0.52224821 -0.42307088
   0.21142484  2.50108314  1.23500085 -0.66581094  0.8111217   0.70196491
  -0.83797473  0.23536153 -0.45694155 -1.68835843 -0.17817882 -0.14882249
  -0.56102598 -0.60714227 -0.6182431  -0.54934317 -0.87456936 -1.28693581
   0.17415266 -1.22470093  0.34076351 -1.17808974 -0.64801049  0.25543416
   1.42168963 -0.77733105 -0.40468538 -0.00383723 -2.41426778 -0.89771551
   0.65747416 -0.04173921 -0.77612114 -1.05099988  1.33182275  0.45550668
  -0.79851466  0.20449917  0.00869674  0.80689704 -0.52269262 -1.06917822
  -0.30134213  0.28299004 -0.72680789  0.27755648 -0.86679631  1.00012195
  -0.78954351 -0.54934883  0.36923081  0.16966993  0.37223512 -1.62987566
  -0.2854479   0.43141723 -0.38336262 -0.17646328  0.7405073  -0.33423463
   0.93998498  0.69573408`

So I got different results in  "llvm" mode and "cuda" mode,  so why?

**Comment by tqchen** [comment]
You will need to create the runtime with ctx=tvm.gpu(0).

**Comment by cocorecoco** [comment]
sorry，I have a copy error， I have set  ctx=tvm.gpu(0)  ， but still getting different results

**Comment by tqchen** [comment]
it would be great if you can give a reproducible script along with your model.  It do not have to be the  original model you have, but as long as you can reproduce the inconsistency, it should be fine.

**Comment by tqchen** [comment]
any updates? would be great if you can provide an reproducible script

**Comment by tqchen** [comment]
close due to inactivity, feel free to reopen
