### ISSUE TITLE
question about mxnet with llvm under python3

### ISSUE THREAD

**Issue by gengtsh** [dmlc/nnvm#258]
when i run from_mxnet.py in tutorial folder, i got the following errors:
could any one help me out?
LLVM = 5.0 my python version = 3.6

output:
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Segmentation fault (core dumped)

when i change my python to 2.7, it runs well. so, is  their a conflict  between LLVM and python3.6 or can mxnet only run with python2.7?

**Comment by tqchen** [comment]
I cannot reproduce this error in my computer, so I assume it is the problem of system LLVM you have
