### ISSUE TITLE
benchmark for gpu run failed when using larger shape

### ISSUE THREAD

**Issue by nkyle04** [dmlc/nnvm#259]
I have change shape to (3, 896, 896) in nnvm/examples/benchmark/gpu_imagenet_bench.py, but it run failed with error:
src/runtime/cuda/cuda_module.cc:93: CUDAError: cuModuleLoadData(&(module_[device_id]), data_.c_str()) failed with error: CUDA_ERROR_INVALID_PTX

It runs fine with shape=(3, 224,224) and (3, 360, 640), but why can't be larger?

**Comment by tqchen** [comment]
cc @Laurawly

**Comment by tqchen** [comment]
close due to inactive issue, in future we can move general dissections to https://discuss.tvmlang.org/
