### ISSUE TITLE
[FRONTEND][COREML] Support Same Padding option in Pooling

### ISSUE THREAD

**Issue by tqchen** [dmlc/nnvm#261]
As in #260, likely can reuse routines from conv2d cc @zhreshold

**Comment by notorca** [comment]
Seems `same` padding in caffe add CoreML have different semantics for conv and pooling. 
http://netaz.blogspot.nl/2016/08/confused-about-caffes-pooling-layer.html
https://github.com/BVLC/caffe/issues/1318

**Comment by zhreshold** [comment]
@notorca Good to know that.
The same padding option is sometimes only available when input shape is ready. What do you suggest to do?

**Comment by tqchen** [comment]
I think we could add support to same pad options by doing shape inference

**Comment by notorca** [comment]
Same padding can be calculated only when input shape is ready. Also CoreML have to options for cases when padding is not symmetrical, `TOP_LEFT_HEAVY`, which  is currently supported as `SAME` in topi.nn.util.get_pad_tuple, and `BOTTOM_RIGHT_HEAVY`.

**Comment by tqchen** [comment]
we can get the input shape by calling shape inference function, given that the data shape is known. The asymmetrical padding can be implemented using the topi.pad operator, which  allows us to pass in specific pad values
