### ISSUE TITLE
[FRONT END] can not support multiple outputs op

### ISSUE THREAD

**Issue by xqdan** [dmlc/nnvm#265]
Hi all,

Front end can not support multiple outputs op in case below:
![image](https://user-images.githubusercontent.com/23742050/33408068-5c4cd1bc-d5af-11e7-9ad0-7e83b5f1131a.png)

```
# for a normal mxnet model, we start from here
mx_sym, args, auxs = mx.model.load_checkpoint('pvanet', 0)
print(mx_sym.debug_str()) #after mx load
# now we use the same API to get NNVM compatible symbol
nnvm_sym, nnvm_params = nnvm.frontend.from_mxnet(mx_sym, args, auxs)
print(nnvm_sym.debug_str()) #after from_mxnet
```
the outputs #after mx load
```
Symbol Outputs:
    output[0]=bbox_pred(0)
    output[1]=cls_prob(0)
    output[2]=proposal(1)
    output[3]=proposal(2)

```
the outputs  #after from_mxnet
```
Symbol Outputs:
    output[0]=avg_pool2d0(0)
    output[1]=softmax1(0)
    output[2]=proposal0(0)
    output[3]=proposal0(0)
```
output[2] and  output[3] are not expected

and proposal is registered as

```
DMLC_REGISTER_PARAMETER(ProposalParam);

NNVM_REGISTER_OP(Proposal)
.describe("Generate region proposals via RPN")
.add_argument("cls_score", "NDArray-or-Symbol", "Score of how likely proposal is object.")
.add_argument("bbox_pred", "NDArray-or-Symbol", "BBox Predicted deltas from anchors for proposals")
.add_argument("im_info", "NDArray-or-Symbol", "Image size and scale.")
.add_arguments(ProposalParam::__FIELDS__())
.set_attr_parser(ParamParser<ProposalParam>)
.set_attr<FGetAttrDict>("FGetAttrDict", ParamGetAttrDict<ProposalParam>)
.set_num_outputs(3)
.set_num_inputs(3)
.set_attr<FNumVisibleOutputs>("FNumVisibleOutputs", [](const NodeAttrs& attrs) {
  return 1;
})
.set_attr<FInferShape>("FInferShape", ProposalInferShape) //sc
.set_attr<FInferType>("FInferType", ElemwiseType<3, 3>)
.set_attr<FListOutputNames>("FListOutputNames", [](const NodeAttrs& attrs) {
   return std::vector<std::string>{"output", "score", "index4bbox"};
 })
.set_support_level(1);
```

**Comment by xqdan** [comment]
there was a issue about FNumVisibleOutputs #246 
seems compose only supports  single visible Output 
```
// compositional logic
void Symbol::Compose(const array_view<const Symbol*>& args,
                     const std::unordered_map<std::string, const Symbol*>& kwargs,
                     const std::string& name) {
  static auto& flist_inputs = Op::GetAttr<FListInputNames>("FListInputNames");
  static auto& fset_attrs = Op::GetAttr<FSetInputVarAttrOnCompose>("FSetInputVarAttrOnCompose");

  // parameter check.
  for (size_t i = 0; i < args.size(); ++i) {
    CHECK_EQ(args[i]->outputs.size(), 1U)
        << "Argument " << i << " is a tuple, single value is required";
  }
```

**Comment by tqchen** [comment]
We do support multiple outputs, except that we need to take subscripten to when referring to each slice. @zhreshold Maybe we could add an example of multiple outputs(e.g. slice?).

**Comment by xqdan** [comment]
what we can see, here is the thing, 
```
# for a normal mxnet model, we start from here
mx_sym, args, auxs = mx.model.load_checkpoint('pvanet', 0)
print(mx_sym.list_outputs())
print(mx_sym)
# now we use the same API to get NNVM compatible symbol
nnvm_sym, nnvm_params = nnvm.frontend.from_mxnet(mx_sym, args, auxs)
print(nnvm_sym)
print(nnvm_sym.list_output_names())
```
```
['bbox_pred_output', 'cls_prob_output', 'proposal_output', 'proposal_index4bbox']
<Symbol group [bbox_pred, cls_prob, proposal, proposal]>
<nnvm.symbol.Symbol object at 0x7f51d2cf5f68>
['avg_pool2d0_output', 'softmax1_output', 'proposal0_output', 'proposal0_output']
```
after load_checkpoint, list_outputs is ok;
but missing slice info in the mx_sym;
in from_mxnet, nnvm_sym is created based on mx_sym rather than mx_sym.list_outputs(),
so slice is missing in both nnvm_sym and nnvm_sym.list_output_names().

**Comment by xqdan** [comment]
```
def _from_mxnet_impl(symbol, graph):
    import pdb
    print(symbol)
    pdb.set_trace()
    if _is_mxnet_group_symbol(symbol):
        return [_from_mxnet_impl(s, graph) for s in symbol]

    name = symbol.attr('name')
    node = graph.get(name, None)
    if node:
        return node
    attr = symbol.list_attr()
    # op_name = symbol.attr('op_name')
    childs = symbol.get_children()
    if childs:
        op_name = symbol.attr('op_name')
        childs = [_from_mxnet_impl(c, graph) for c in _as_list(childs)]
        childs = [x for y in childs for x in _as_list(y)]  # expand group symbol
        node = _convert_symbol(op_name, childs, attr)
    else:
        op_name = json.loads(symbol.tojson())['nodes'][0]['op']
        node = _sym.Variable(name=name, **attr)
    graph[name] = node
    return node
```
<Symbol group [bbox_pred, cls_prob, proposal, **proposal**]>
when traversing the last mx symbols above to build this graph, 
before transform to nnvm symbols, we have outputs outputs ,
```
(Pdb) p symbol.list_outputs()
['proposal_index4bbox']
```
then it'll find node with name "proposal" in graph,  because there has been one already, so return node directly with missing outputs info at this point.

**Comment by xqdan** [comment]
--- a/python/nnvm/frontend/mxnet.py
+++ b/python/nnvm/frontend/mxnet.py
@@ -327,9 +327,10 @@ def _from_mxnet_impl(symbol, graph):
         return [_from_mxnet_impl(s, graph) for s in symbol]

     name = symbol.attr('name')
+    index = symbol.attr('index')
     node = graph.get(name, None)
     if node:
-        return node
+        return node[int(index)]
     attr = symbol.list_attr()
     # op_name = symbol.attr('op_name')
     childs = symbol.get_children()
diff --git a/src/core/symbolic.cc b/src/core/symbolic.cc
index 2cbcad7..5608e1e 100755
--- a/src/core/symbolic.cc
+++ b/src/core/symbolic.cc
@@ -269,10 +269,12 @@ void Symbol::Compose(const array_view<const Symbol*>& args,
   static auto& fset_attrs = Op::GetAttr<FSetInputVarAttrOnCompose>("FSetInputVarAttrOnCompose");

   // parameter check.
+  #if 0
   for (size_t i = 0; i < args.size(); ++i) {
     CHECK_EQ(args[i]->outputs.size(), 1U)
         << "Argument " << i << " is a tuple, single value is required";
   }
+  #endif

   for (const auto& kv : kwargs) {
     CHECK_EQ(kv.second->outputs.size(), 1U)
@@ -496,7 +498,10 @@ bool Symbol::GetAttr(const std::string& key, std::string* out) const {
       *out = "null";  // use null with json
     }
     return true;
-  }
+  } else if (key == "index") {
+    *out = std::to_string(outputs[0].index);
+     return true;
+   }
   auto it = node->attrs.dict.find(key);
   if (it == node->attrs.dict.end()) return false;
   *out = it->second;
diff --git a/src/top/nn/nn.cc b/src/top/nn/nn.cc
index 8533861..1c60469 100755
--- a/src/top/nn/nn.cc
+++ b/src/top/nn/nn.cc
@@ -173,7 +173,7 @@ NNVM_REGISTER_OP(Proposal)
 .set_num_outputs(3)
 .set_num_inputs(3)
 .set_attr<FNumVisibleOutputs>("FNumVisibleOutputs", [](const NodeAttrs& attrs) {
-   return 1;
+   return 3;
  })

can be fixed by this

**Comment by zhreshold** [comment]
The index hack will do the trick. For the check in Compose, the multiple output should be sliced before composing so the check is still valid? 
E.g. 
```
a = sym.split(...)
b = sym.yyy(a[0])
c = sym.zzz(a[1], a[2])
```
@xqdan @tqchen

**Comment by zhreshold** [comment]
Still the index trick will require mxnet to be updated, which is not ideal. @tqchen Do you have any idea how to get the index in mxnet? Currently I don't find any way to do that without modifying mxnet side.

**Comment by tqchen** [comment]
since we are doing transformation on the pass, it is likely we can get the index from its reference(i.e. n.inputs[i][1] contains the index of the node it refers to)

**Comment by xqdan** [comment]
thanks for fixing, it works fine
