### ISSUE TITLE
Updating ONNX version to 1.0

### ISSUE THREAD

**Issue by bonotake** [dmlc/nnvm#269]
How about going to update ONNX version to 1.0?

https://github.com/onnx/onnx/releases/tag/v1.0
https://aws.amazon.com/jp/blogs/ai/announcing-the-availability-of-onnx-1-0/

**Comment by tqchen** [comment]
@zhreshold can you look into this?

**Comment by tqchen** [comment]
https://github.com/dmlc/nnvm/pull/294
