### ISSUE TITLE
nnvm.compiler performance issue

### ISSUE THREAD

**Issue by lanhin** [dmlc/nnvm#281]
Hi there,
    I used the tutorial script [`Compile MXNet Models`](http://nnvm.tvmlang.org/tutorials/from_mxnet.html#sphx-glr-tutorials-from-mxnet-py) to test the performance of ResNet-50. Comparing to the [MxNet model](https://github.com/tornadomeet/ResNet/blob/master/predict/predict.py), it's 20%-30% slower. Is this OK? Is there any measure I can take to optimize the nnvm script, like fusing operations? This might be an awkward question, but I'm a tyro. 
Any advice is appreciated. Thanks!

The time measuring code for mxnet:
```python
start = time.time()
for i in range(times):
    exe.forward(is_train=False)
mx.ndarray.waitall()
end = time.time()
```

And for NNVM+TVM:
```python
start = time.time()
for i in range(times):
    m.run()
end = time.time()
```

**Comment by tqchen** [comment]
see https://github.com/dmlc/nnvm/issues/230  one thing to note is to turn on the options in the benchmark script as in https://github.com/dmlc/nnvm/blob/master/examples/benchmark/gpu_imagenet_bench.py

**Comment by guopinglong** [comment]
Play with the compiler options of gpu_imagenet_bench.py
Tune the parameters of of convolution schedules for your hardware.  Entry is here: tvm/topi/python/topi/cuda/conv2d_nchw.py
You can also play with the NNVM fusion logic, but the current implementation has already a good job for graphs like Resnet.
After these steps, you should be able to get comparable results with mxnet inference.

The current conv2d schedule assumes a not very efficient computation graph. So, if conv2d computations could be replaced with winograd/gemm implementations, further performance results beyond mxnet are possible.
Hope these helps :-)
