### ISSUE TITLE
support MultiBoxPrior

### ISSUE THREAD

**Issue by kaishijeng** [dmlc/nnvm#285]
@zhreshold 

Does NNVM MXNET frontend support MultiBoxPrior?
I got the following error when importing mobilenet_ssd pretrained model from
https://github.com/zhreshold/mxnet-ssd/releases/download/v0.7-alpha/mobilenet-ssd-512.zip

NotImplementedError: Operator: _contrib_MultiBoxPrior is not supported in nnvm

Thanks,

**Comment by zhreshold** [comment]
No, it's not currently supported in nnvm

**Comment by kaishijeng** [comment]
Do you have a plan to support it? With it, we can test object detection performance using NNVM.
Thanks,

**Comment by kaishijeng** [comment]
@zhreshold 

   Any comment on this request?

Thanks,

**Comment by zhreshold** [comment]
@kaishijeng On what device do you want to test? Currently writing custom operator is not on my recent task list.

**Comment by kaishijeng** [comment]
Firefly 3399 which has 2xA72 and 4xA53.

Thanks,.

**Comment by kaishijeng** [comment]
@zhreshold 

Any plan to implement this in near future?

Thanks,

**Comment by kaishijeng** [comment]
@zhreshold 

Any  update on this operator support? 
If you are still busy, can you provide  a guidance how to implement it and I can try it myself?
Thanks,

**Comment by zhreshold** [comment]
I am blocked by other stuffs recently, so you are very welcome to try it youself first.
Basically these operators are quite simple and light weight in computation. You can refer to contrib/cblas for wiring external functions.

**Comment by zhreshold** [comment]
check out https://github.com/dmlc/tvm/issues/908

**Comment by tqchen** [comment]
Let us move the discussion to  dmlc/tvm#908 to minimize the number of issues
