### ISSUE TITLE
graph_runtime.create

### ISSUE THREAD

**Issue by AndyQi93** [dmlc/nnvm#299]
Can I run this on CPU by llvm?
Now the deploy_graph is existing， should I change the function "graph_runtime.create" ?

#------------
module = graph_runtime.create(deploy_graph, lib, tvm.gpu(0))
-------------#

**Comment by AndyQi93** [comment]
By the way, when I generate the deploy_graph, I used the following code:
  
deploy_graph, lib, params = nnvm.compiler.build(
    compute_graph, target="llvm", shape={"x": shape}, dtype="float32")

**Comment by srkreddy1238** [comment]
Yes. If the build is compiled with llvm support.
All you need to do is choose target as "llvm" and the context as cpu(0).

**Comment by AndyQi93** [comment]
thx!

**Comment by AndyQi93** [comment]
When using llvm,  can nnvm print out the the generated device code like use cuda that through the code of "print(lib.imported_modules[0].get_source())"?

**Comment by siju-samuel** [comment]
print(lib.getsource()) will work for LLVM. You can remove imported_modues[0]

**Comment by srkreddy1238** [comment]
Yes, llvm also support device code printing.
