### ISSUE TITLE
install nnvm in Mac erro???Expected in: flat namespace  

### ISSUE THREAD

**Issue by chenqy4933** [dmlc/nnvm#332]
After I compile the nnvm ,I import it from python ,but the erro happened,it just like the lib is not complie completely.
the erro is 
>>> import nnvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nnvm/__init__.py", line 6, in <module>
    from . import _base
  File "nnvm/_base.py", line 47, in <module>
    _LIB = _load_lib()
  File "nnvm/_base.py", line 39, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/chenqiyou/nnvm/python/nnvm/../../lib/libnnvm_compiler.dylib, 6): Symbol not found: __ZTIN3tvm4NodeE
  Referenced from: /Users/chenqiyou/nnvm/python/nnvm/../../lib/libnnvm_compiler.dylib
  Expected in: flat namespace
 in /Users/chenqiyou/nnvm/python/nnvm/../../lib/libnnvm_compiler.dylib

how can solve it ?
thank you!!!!!!

**Comment by srkreddy1238** [comment]
How about TVM installation did you install latest ?

Siva

**Comment by chenqy4933** [comment]
@srkreddy1238 yes ,I forget to install TVM before,,thank you very much!!

**Comment by tqchen** [comment]
please close the issue if it is already resolved, thanks!
