### ISSUE TITLE
C++ compile use build deploy.so erro!!!!!

### ISSUE THREAD

**Issue by chenqy4933** [dmlc/nnvm#335]
I use the the method of deploy.md in C++,link with lintvm.dylib ,but a runtime erro happend when process the line below
 
  tvm::runtime::Module mod = (*tvm::runtime::Registry::Get("tvm.graph_runtime.create"))(json_data, mod_syslib, device_type, device_id);

the erro is 
  
  libc++abi.dylib: terminating with uncaught exception of type dmlc::Error: [16:15:11] src/runtime/graph/graph_runtime.cc:187: Check failed: bitmask == 1|2|4|8 (0 vs. 15) invalid format

I don't konw the detail of the src code ,so I can,t fix it .
can any body solve it ,appreciate it very much!!!

@WolffyChen have you succeed in running this program ?

**Comment by tqchen** [comment]
A typical error in here is that you passed in the file name, instead of the real json string conctent into the json_data

**Comment by baileyqbb** [comment]
Hi, I'm facing the same issue using C++. Any update on it?

As mentioned by @tqchen, I've printed the json_data after loading the json file, to confirm json_data loads the string content of the json file, but still get the same error.
