### ISSUE TITLE
How to use the NNVM complied lib.so in android platform with C++ project???

### ISSUE THREAD

**Issue by chenqy4933** [dmlc/nnvm#341]
In the NNVM tutorial There is only python example of run in mali device with rpc，Now I want to run it on android with C++ link the NNVM complied lib , I am not sure whether I should cross-complie the TVM and get device-support libtvm.so , and link it into my C++ project just like the method in deploy.md? And how I cross-complie the TVM project?

@tqchen must I cross-complie the TVM into android ? My phone is not rooted , I can't complie libtvm_runtime.so on android.

**Comment by tqchen** [comment]
see http://www.tvmlang.org/2017/11/08/android-rpc-introduction.html   You can use NDK on your host to cross-compile most of the stuffs, cc @yzhliu
