### ISSUE TITLE
Compiler C API

### ISSUE THREAD

**Issue by sergiyprotsiv** [dmlc/nnvm#342]
Hi,

Thanks a lot for your work on NNVM and TVM, it really is a fantastic undertaking.

I want to use it as part of a larger application, which would build up the NNVM graph dynamically through the C api. However, currently doing anything with this graph requires going to Python before the functions can be executed.

I am wondering whether it would be possible to expose the compilation as a C (or C++) API, similarly to the `build` and `lower` functions in Python. The essential operation would be to transform a GraphHandle into a FunctionHandle, which could then be callable from C.

I have tried to implement this process myself and there seem to be two main issues with this:
- Many of the computes/schedules are only defined in Python (as discussed in https://github.com/dmlc/nnvm/issues/213). I was able to register the compute/schedule for a simple function like "elemwise_add" via C++, but could not really test the results because of the second issue:
- The compiler API is undocumented and in flux, for example https://github.com/dmlc/nnvm/pull/338 added a mysterious master_idx input to CompileEngine::Lower and I could not find what that refers to.

With this, I really have two questions:
- Is a C API to the compiler in plans for the project?
- If it is possible to provide a very basic example of accomplishing the Graph->PackedFunc task using the current C++ APIs, it would be greatly appreciated even if it is in no way supported.

Thanks,
Sergiy

**Comment by tqchen** [comment]
I think the major issue is same as #213 Once we put the schedules into C++, the nnvm compiler registration side is not as hard. 

The plan is that we can do C API without adding new API headers, but relies on the PackFunc system so it is readily available to front-end runtime.

We can find relevant effort in here: https://github.com/dmlc/tvm/pull/763 and https://github.com/dmlc/tvm/pull/667

**Comment by tqchen** [comment]
I will mark this as duplicate as #213 and let us move the discussion there.

**Comment by tqchen** [comment]
OK, given there is enough attention about this, we decided to put it in our roadmap and create a master issue here https://github.com/dmlc/nnvm/issues/343
