### ISSUE TITLE
Build failure on Windows because of old submodule

### ISSUE THREAD

**Issue by AtuNuka** [dmlc/nnvm#351]
Hi,

NNVM/TVM is failed to build in newest version on Windows in below environment.

NNVM Commit: dd4f6a9f95a45068252b2f32f7e07d1b07596740
OS: Windows 10 Pro 64bit
Compiler: Visual Studio 15 2017

```
2>C:\Users\nuka\nnvm\tvm\src\runtime\workspace_pool.cc(31): error C2059: syntax error: '.'
2>C:\Users\nuka\nnvm\tvm\src\runtime\workspace_pool.cc(31): error C2143: syntax error: missing ';' before '}'
2>C:\Users\nuka\nnvm\tvm\src\runtime\workspace_pool.cc(32): error C2059: syntax error: 'if'
2>C:\Users\nuka\nnvm\tvm\src\runtime\workspace_pool.cc(32): error C2143: syntax error: missing ';' before '{'
2>C:\Users\nuka\nnvm\tvm\src\runtime\workspace_pool.cc(32): error C2447: '{': missing function header (old-style formal list?)
2>C:\Users\nuka\nnvm\tvm\src\runtime\workspace_pool.cc(41): error C2059: syntax error: 'else'
2>C:\Users\nuka\nnvm\tvm\src\runtime\workspace_pool.cc(41): error C2143: syntax error: missing ';' before '{'
2>C:\Users\nuka\nnvm\tvm\src\runtime\workspace_pool.cc(41): error C2447: '{': missing function header (old-style formal list?)

<snip>
```

This is because ```tvm/src/runtime/workspace_pool.cc``` uses GNU struct initialization. And it seems that this has already been fixed in tvm project.

https://github.com/dmlc/tvm/commit/68b9aa9a05b5914a7c5cf2fce9fda13f4ea6f503#diff-06c69bd0cdfc13afd730c7658460da97

So, the real problem is that NNVM is pointing to the old TVM commit.
I'd appreciate to update a submodule TVM to the latest or proper version.

Thanks.

**Comment by PENGUINLIONG** [comment]
Before submodule is updated, you can enter the `tvm` directory, `git pull` and rebuild, to use the latest version.

**Comment by AtuNuka** [comment]
Thanks.
I will update manually for now.

I think it may be great if this operation is added to the Installation Guide.
Possibly, there may be people who have same issues.

If it is a general way, I'll send pull requests which adds this operations to NNVM Installation Guide.
But I'm not sure about it.

**Comment by PENGUINLIONG** [comment]
Yes, you can do this every time you met much problem (outdated submodule) no matter what repo you are dealing with.

**Comment by PENGUINLIONG** [comment]
You should also denote that, the commit set in submodule is the *recommended* setting. Always using the latest commit might lead to compilation error or something else, since maybe NNVM is not yet adapted for it. It should only be considered as a solution of the last resort.

**Comment by AtuNuka** [comment]
OK, I will add these advice you mentioned.
The issue itself has already been solved, so close this issue.
I will send pull request later. thanks.
