### ISSUE TITLE
problem for from_coreml.py image transform part

### ISSUE THREAD

**Issue by wl3b10s** [dmlc/nnvm#353]
i think.....

image input and tranform code:  x = np.transpose(img,(2,0,1))[np.newaxis, :]

should be the code like from_mxnet.py
"
def transform_image(image):
    image = np.array(image) - np.array([123., 117., 104.])
    image /= np.array([58.395, 57.12, 57.375])
    image = image.transpose((2, 0, 1))
    image = image[np.newaxis, :]
    return image
"

**Comment by tqchen** [comment]
#354
