### ISSUE TITLE
[CoreML] Support Split

### ISSUE THREAD

**Issue by drkoller** [dmlc/nnvm#358]
I'd like to import some Core ML models that include "split" and other layer types that produce multiple outputs. However, `nnvm.frontend.from_coreml()` currently throws an exception for these layers with more than one output. What would be involved in addressing this?

**Comment by tqchen** [comment]
Split is not necessary and this is only the problem of improving the frontend to handle split

**Comment by tqchen** [comment]
move to https://github.com/dmlc/tvm/issues/1187
