### ISSUE TITLE
[Convolution] What is the status of NHWC ?

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/nnvm#360]
What is the status of NHWC layout support in NNVM & TVM  ?

If not, Can we change the input, weights, bias layout to NCHW and use ?

Siva

**Comment by tqchen** [comment]
it mainly boils down to nhwc support for topi operators

**Comment by srkreddy1238** [comment]
"it mainly boils down to nhwc support for topi operators"
Does it mean I should convert the layout while importing ?

As I see [assert](https://github.com/dmlc/nnvm/blob/96b79342cc2aa81757c7a6335c8fc331c3f070fb/python/nnvm/top/nn.py#L73) here about other layouts.

**Comment by tqchen** [comment]
NO, we should support nhwc layout in topi, and then improve nnvm to be able to use the nhwc version. I think @masahi mentioned that he have some in-house extension that  already support nhwc

**Comment by masahi** [comment]
yes, I have working NHWC layout support in topi and nnvm. 

But changes are not clean and they only cover my use case (conv, pooling, upsampling, softmax).  If that is ok, I can send a pr.

**Comment by srkreddy1238** [comment]
Pls share, we could improve together it to make it clean.

Siva

**Comment by masahi** [comment]
ok, will send a pr this weekend.

**Comment by srkreddy1238** [comment]
Thanks
