### ISSUE TITLE
How to register a new operator

### ISSUE THREAD

**Issue by pallabdatta** [dmlc/nnvm#361]
Hi @tqchen 

I have a class defined in pyTorch called "Shift", which has 1 input tensor and generates 1 output tensor. It has a internal parameter lets say "M". Now the backward function has a gradient computed as 
grad = 2*M
I have exported the pytorch model using ONNX. I can import it via the from_onnx command.
Now when I try to do:

graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)
for target = 'llvm'
it gives me this error message:

/Users/pallabdatta/nnvm/include/nnvm/./op.h:532: Check failed: idx < data_.size() && data_[idx].second Attribute FTVMCompute has not been registered for Operator Shift

Stack trace returned 10 entries:
[bt] (0) 0   libnnvm_compiler.dylib              0x0000000119339448 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libnnvm_compiler.dylib              0x000000011933e0aa _ZNK4nnvm5OpMapINSt3__18functionIFN3tvm5ArrayINS3_6TensorEvEERKNS_9NodeAttrsERKS6_SB_EEEEixEPKNS_2OpE + 378
[bt] (2) 2   libnnvm_compiler.dylib              0x000000011933b412 _ZN4nnvm8compiler13CompileEngine7DoLowerENS_5GraphERKN3tvm5ArrayINS3_6TensorEvEERKNSt3__112basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEEPKNS_2OpERKNS_9NodeAttrsE + 5442
[bt] (3) 3   libnnvm_compiler.dylib              0x0000000119338332 _ZN4nnvm8compiler13CompileEngine5LowerENS_5GraphERKN3tvm5ArrayINS3_6TensorEvEERKNSt3__112basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEEPKNS_2OpERKNS_9NodeAttrsE + 434
[bt] (4) 4   libnnvm_compiler.dylib              0x00000001193380f6 _ZN4nnvm8compiler10GraphLowerENS_5GraphERKN3tvm5ArrayINS2_6TensorEvEERKNSt3__112basic_stringIcNS8_11char_traitsIcEENS8_9allocatorIcEEEEPKNS_2OpERKNS_9NodeAttrsE + 342
[bt] (5) 5   libnnvm_compiler.dylib              0x000000011935a182 _ZN4nnvm8compiler16GraphFuseCompileENS_5GraphE + 9938
[bt] (6) 6   libnnvm_compiler.dylib              0x0000000119353c71 _ZNSt3__128__invoke_void_return_wrapperIN4nnvm5GraphEE6__callIJRPFS2_S2_ES2_EEES2_DpOT_ + 209
[bt] (7) 7   libnnvm_compiler.dylib              0x0000000119353b62 _ZNSt3__110__function6__funcIPFN4nnvm5GraphES3_ENS_9allocatorIS5_EES4_EclEOS3_ + 18
[bt] (8) 8   libnnvm_compiler.dylib              0x0000000119429658 _ZN4nnvm11ApplyPassesENS_5GraphERKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEE + 1448
[bt] (9) 9   libnnvm_compiler.dylib              0x00000001194189f6 NNGraphApplyPasses + 566

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pallabdatta/nnvm/python/nnvm/compiler/build_module.py", line 251, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/Users/pallabdatta/nnvm/python/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/Users/pallabdatta/nnvm/python/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: [19:37:32] /Users/pallabdatta/nnvm/include/nnvm/./op.h:532: Check failed: idx <

I have registered this class param in /nnvm/include/nnvm/top/nn.h

struct ShiftParam : public dmlc::Parameter<ShiftParam> {
  int M;
  DMLC_DECLARE_PARAMETER(ShiftParam) {
    DMLC_DECLARE_FIELD(M).set_lower_bound(-31).set_default(0)
        .describe("4 bit Integer scalar. Most significant bit.");
  }
};
and the corresponding entry in /nnvm/src/top/nn/nn.cc
as

DMLC_REGISTER_PARAMETER(ShiftParam);

NNVM_REGISTER_OP(Shift)
.describe(R"code(Perform bit shift operation by shifting A by B bits left if B is positive shift left.

`y = x * 2^ shift_bits`

)code" NNVM_ADD_FILELINE)
.add_argument("data", "Tensor", "Input data.")
.add_arguments(ShiftParam::__FIELDS__())
.set_attr_parser(ParamParser<ShiftParam>)
.set_attr<FGetAttrDict>("FGetAttrDict", ParamGetAttrDict<ShiftParam>)
.set_num_inputs(1)
.set_num_outputs(1)
.set_attr<FInferShape>("FInferShape", ElemwiseShape<1, 1>)
.set_attr<FInferType>("FInferType", ElemwiseType<1, 1>)
.set_attr<FGradient>(
  "FGradient", [](const NodePtr& n,
                  const std::vector<NodeEntry>& ograds) {
    // y = 2^M(x)
    // grad = 2*M
    const ShiftParam& param = nnvm::get<ShiftParam>(n->attrs.parsed);
    NodeEntry zero = MakeNode("zeros_like", n->attrs.name + "_grad_zero",
                              {n->inputs[0]});
                              
    return std::vector<NodeEntry>{
      MakeNode("elemwise_mul", n->attrs.name + "_add_grad", {zero}, {{"scalar", std::to_string(2*param.M)}})
    };
})  
.set_support_level(1);

Am I registering this wrongly inside NNVM? Can you please help. Is there a formal writeup/document on this process..? thanks for sharing.
thanks a lot in advance.

**Comment by pallabdatta** [comment]
I really don't want the NNGraphApplyPasses to be invoked for this node..
Please help.

**Comment by tqchen** [comment]
You can try register the other information from python side, see https://github.com/dmlc/nnvm/blob/master/python/nnvm/top/tensor.py#L46

**Comment by pallabdatta** [comment]
Hi @tqchen 

I did register it under nnvm/python/nnvm/top/nn.py and now after re-installing nnvm again when I try to build the graph it says:

File "<stdin>", line 1, in <module>
  File "/Users/pallabdatta/nnvm/python/nnvm/compiler/build_module.py", line 251, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/Users/pallabdatta/nnvm/python/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/Users/pallabdatta/nnvm/python/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "tvm/_ffi/_cython/./function.pxi", line 39, in core.tvm_callback
  File "/Users/pallabdatta/nnvm/python/nnvm/top/nn.py", line 35, in compute_BitShift
    return topi.nn.BitShift(inputs[0], attrs.get_int("shift_bits"))
AttributeError: module 'topi.nn' has no attribute 'BitShift'

I think now it wants me to register this somewhere in tvm?
Can you tell me exactly where to plugin the next piece of code?
thanks so much for your prompt response.
-- pallab

**Comment by tqchen** [comment]
You can implement bitshift at topi, or simply implement them with TVM. NOTE that there is already a shift_left and right functions in topi

**Comment by pallabdatta** [comment]
Thanks so much..can you point me to those? Is there a issue track or document which captures the entire process of registering a new Op.?

**Comment by tqchen** [comment]
Unfortunately there is no clear document on this, but you are pretty close.

Now, top.nn.py tries to implement these operators, and we need to create TVM functions to implement them. topi is a library that helps you to do these, for bit shifting, see https://github.com/dmlc/tvm/blob/master/topi/python/topi/math.py#L128

**Comment by pallabdatta** [comment]
Yep..I got it working..!! thank you..!!

**Comment by pallabdatta** [comment]
I can see the shift_left and shift_right in TVM. Where is the corresponding Op registered in NNVM?

**Comment by srkreddy1238** [comment]
TVM operators are like low-level. There need not be a corresponding NNVM exact map.

One or more TVM operators will be used while creating NNVM operator.

Your corrent operator you may use existing TVM shift operators by creating new NNVM operator.

Siva
