### ISSUE TITLE
[matmul] Some queries

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/nnvm#368]
1:

referring to [matrix_op](https://github.com/dmlc/nnvm/blob/535d63e8faf4dfb339d91df686ccaecd3552311c/src/top/tensor/matrix_op.cc#L36)

Out shape with input shapes [1, 2048] and [2048, 1008] resulted in [1, 1, 1008] . 
Is this expected ?

2:
Where is the compute and schedule defined for "matmul" operator in nnvm ?

Siva

**Comment by tqchen** [comment]
documented here https://github.com/dmlc/nnvm/blob/535d63e8faf4dfb339d91df686ccaecd3552311c/src/top/tensor/matrix_op.cc#L53

**Comment by srkreddy1238** [comment]
I saw that in source documentation and still unclear. A 2D multiplication goes wrong as explained above.

 My other concern of compute & schedule not found which is raising error while building the graph.

Siva
