### ISSUE TITLE
[Conv2D] NHWC InferShape Issue

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/nnvm#370]
Ref. https://github.com/dmlc/tvm/pull/896

ConvertLayout in InferShape require different way for Data and Weights conversion for NHWC format.

Siva

**Comment by masahi** [comment]
I'm preparing a PR to adapt nnvm to NHWC layout.

My modified ConvertLayout is here 
https://github.com/masahi/nnvm/blob/upstreaming-nhwc/src/top/nn/nn_common.h#L43

will send a pr soon.

**Comment by srkreddy1238** [comment]
Complexity increased with more combinations.

I think initial design was to have an intermediate (from_layout -> NCHW  -> to_layout) to support all formats. I think we should keep the original design.

Siva

**Comment by masahi** [comment]
Yeah I know, I didn't change that. see here (note how I use ConvertLayout)
https://github.com/masahi/nnvm/blob/upstreaming-nhwc/src/top/nn/convolution.cc

But I have to admit that,  this is the part that is not clean.

**Comment by srkreddy1238** [comment]
[This](https://github.com/masahi/nnvm/blob/ee2e9b4ba525c0845bf3ddbdf6287b1fa8582284/src/top/nn/convolution.cc#L51
) looks perfectly fine.

I was talking about the below part.
```
 if (src_layout == kNCHW && dst_layout == kNHWC && !is_weight) {
      //NCHW -> NHWC
      dst[1] = src[2];
      dst[2] = src[3];
      dst[3] = src[1];
    }
    else if (src_layout == kNCHW && dst_layout == kNHWC && is_weight) {
      //KCRS -> RSCK
      dst[0] = src[2];
      dst[1] = src[3];
      dst[2] = src[1];
      dst[3] = src[0];
    }
    else if (src_layout == kNHWC && dst_layout == kNCHW && !is_weight) {
      //NHWC -> NCHW
      dst[1] = src[3];
      dst[2] = src[1];
      dst[3] = src[2];
    }
    else if (src_layout == kNHWC && dst_layout == kNCHW && is_weight) {
      //RSCK -> KCRS
      dst[0] = src[3];
      dst[1] = src[2];
      dst[2] = src[0];
      dst[3] = src[1];
    }
```

Instead of multiple combinations across NCHW, NHWC & is_weight, I think we should keep original switch case (which convert source_layout -> NCHW -> dst_layout) with is_weight check only for case NHWC:

Siva

**Comment by masahi** [comment]
ah, ok.
I replaced switch with if to make it clearer what I am doing. The original one was not clear to me.

**Comment by srkreddy1238** [comment]
Here is the PR https://github.com/dmlc/nnvm/pull/372
I verified with my NHWC model and it works fine.

Siva
