### ISSUE TITLE
[padding] SAME / VALID Support

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/nnvm#371]
[Ref.](https://github.com/dmlc/tvm/blob/6224779dc03ee7b3e36274a1265daff8f5690787/topi/python/topi/nn/util.py#L66)

TVM operator implementation support 'int or str' to support direct tuple or string 'SAME/VALID'. 

But NNVM operator implementation [nn.h](https://github.com/dmlc/nnvm/blob/535d63e8faf4dfb339d91df686ccaecd3552311c/include/nnvm/top/nn.h#L137) doesn't handle 'SAME/VALID' 

Not sure how do we handle this !!

Do we make extra arg 'padding_scheme' to pass 'SAME/VALID' ??

Siva

**Comment by tqchen** [comment]
The current decision is to not support it in the core language, but try to be able to convert things correctly when we import.

**Comment by srkreddy1238** [comment]
This is similar to https://github.com/dmlc/nnvm/issues/261

Siva

**Comment by tqchen** [comment]
Yah, as long as the behavior is supported consistent with the frontend, it works fine, a contribution is welcomed, we can move to #261 to minimize the number of opened issues
