### ISSUE TITLE
[matmul] Some queries

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/nnvm#373]
referring to matrix_op i checked the documentation @ [matrix_op.cc](https://github.com/dmlc/nnvm/blob/535d63e8faf4dfb339d91df686ccaecd3552311c/src/top/tensor/matrix_op.cc#L53)

1: I saw that in source documentation and still unclear. A 2D multiplication goes wrong as explained below.

Out shape with input shapes [1, 2048] and [2048, 1008] resulted in [1, 1, 1008] .
Is this expected ? 

2: My other concern of compute & schedule not found which is raising error while building the graph.

Any help appreciated.

Siva

**Comment by tqchen** [comment]
@kevinthesun can you followup on this issue?

**Comment by kevinthesun** [comment]
There are some issues in matmul. shape is not correct. Will fix this together in https://github.com/dmlc/nnvm/pull/334

**Comment by tqchen** [comment]
@kevinthesun fix there is a bug need to be fixed, we can just submit a separate PR

**Comment by kevinthesun** [comment]
Will do that.
