### ISSUE TITLE
TVM run on android

### ISSUE THREAD

**Issue by dayanandasiet** [dmlc/nnvm#374]
Hi Team,

Will you give hint how we can make android application run compiled tvm library run ? not using RPC

**Comment by tqchen** [comment]
@yzhliu do you think if we can make a clear tutorial on that?

**Comment by yzhliu** [comment]
By using RPC, you upload the compiled lib to the device, make android_rpc app (based on tvm4j) load the lib. This approach help you to tune/debug on your desktop and test on the device.

Once you have finished tuning, you can (cross-) compile the tvm library (target to your android device) and load it by java (a simple example: https://github.com/dmlc/tvm/blob/master/jvm/core/src/test/java/ml/dmlc/tvm/ModuleTest.java#L37). tvm4j allows you to load compiled tvm library in you android application. What you need to do is including tvm4j as a dependency of your Android/Java project.

We can make the tutorial more clear.

**Comment by dayanandasiet** [comment]
@yzhliu

Thanks for hint, will work on the same.

**Comment by tqchen** [comment]
closing for now
