### ISSUE TITLE
Intel GPU FP16 Perf

### ISSUE THREAD

**Issue by long-gao** [dmlc/nnvm#380]
I was trying to run ResNet18 with different opt_level options for float16. Somehow opt_level 0 is much faster than opt_level 1/2. Any comments or suggestions are welcome.

Some details:
Code: mali_imagenet_bench.py from https://github.com/merrymercy/tvm-mali
OS: ubuntu
GPU: Intel® Processor Graphics Gen9
Inference time per image: ~2 second with opt_level 1/2 vs. ~180 ms with opt_level 0

**Comment by yidawang** [comment]
cc @Laurawly

**Comment by tqchen** [comment]
that likely means the fp16 fusing caused further fused operation not working well on the opencl code. but maybe @merrymercy can comment more

**Comment by Laurawly** [comment]
@tqchen It seems that by using im2col schedule in mali instead of the default spatialpack scheduler, opt_level 2 does run faster than opt_level 1/0.

**Comment by tqchen** [comment]
close due to inactive issue, in future general discussions can be moved to https://discuss.tvmlang.org/
