### ISSUE TITLE
Mul broadcast problem

### ISSUE THREAD

**Issue by pallabdatta** [dmlc/nnvm#387]
Hi @tqchen 

I have a small test network in PyTorch and we export it in ONNX format. It has only 4 layers. 
But somehow I am hitting a problem.  

# Standard Import for torch
import torch
import torchvision
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

# Parameters
target_file = os.path.expanduser("~/Desktop/minnet.onnx")
if os.path.exists(target_file):
    os.remove(target_file) # Clear file so can test if actually created

def param(*size):
    return torch.nn.Parameter(torch.Tensor(*size).uniform_(-127,127))

# Test run
class Testnet(nn.Module):
    def __init__(self):
        super(Testnet, self).__init__()
        self.np_conv1_weight = param(128,3,3,3)
        self.np_conv1_bias = param(1,128,1,1)
        self.np_conv1_scale = param(1,128,1,1)

    def forward(self, x):
        # Conv 1
        x = op.conv2d(x, self.np_conv1_weight, padding=1)
        x = op.add(x, self.np_conv1_bias)
        x = op.mul(x, self.np_conv1_scale)
        
        # Max 1
        x = op.max_pool2d(x, kernel_size=2)

        return x

# Build network
net = Testnet()

# Test running network
dummy_input = Variable(torch.Tensor(2, 3, 32, 32).zero_().floor(),
    requires_grad=True)

# Save
torch.onnx.export(net, dummy_input, target_file, export_params=True)
import onnx

# Load
print('\n\n Trying to load (will print graph below if successful) \n\n')
onnx_model = onnx.load(target_file)
print(onnx_model)

In python when I do the following:

import nnvm
import tvm
import onnx
import numpy as np

onnx_graph = onnx.load('minnet.onnx')
sym, params = nnvm.frontend.from_onnx(onnx_graph)

a = np.random.randn(2,3,32,32)
import nnvm.compiler
target = 'llvm'
shape_dict = {'input_0': a.shape}
opt_level = 0
with nnvm.compiler.build_config(opt_level=opt_level):
    graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)

I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/pallabdatta/nnvm/python/nnvm/compiler/build_module.py", line 228, in build
    ishape, _ = graph_util.infer_shape(graph, **shape)
  File "/Users/pallabdatta/nnvm/python/nnvm/compiler/graph_util.py", line 31, in infer_shape
    graph = graph.apply("InferShape")
  File "/Users/pallabdatta/nnvm/python/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/Users/pallabdatta/nnvm/python/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: [15:25:14] /Users/pallabdatta/nnvm/src/top/nn/pooling.cc:36: Check failed: dshape.ndim() == 4U (6 vs. 4) Pooling: Input data should be 4D

Stack trace returned 9 entries:
[bt] (0) 0   libnnvm_compiler.dylib              0x000000011a53497b dmlc::StackTrace() + 299
[bt] (1) 1   libnnvm_compiler.dylib              0x000000011a53470f dmlc::LogMessageFatal::~LogMessageFatal() + 47
[bt] (2) 2   libnnvm_compiler.dylib              0x000000011a5d179e nnvm::top::Pool2DInferShape(nnvm::NodeAttrs const&, std::__1::vector<nnvm::TShape, std::__1::allocator<nnvm::TShape> >*, std::__1::vector<nnvm::TShape, std::__1::allocator<nnvm::TShape> >*) + 1454
[bt] (3) 3   libnnvm_compiler.dylib              0x000000011a67b087 nnvm::Graph nnvm::pass::(anonymous namespace)::InferAttr<nnvm::TShape, nnvm::pass::(anonymous namespace)::$_0::operator()(nnvm::Graph) const::'lambda'(nnvm::TShape const&), std::nullptr_t>(nnvm::Graph&&, nnvm::TShape, char const*, char const*, char const*, char const*, char const*, nnvm::pass::(anonymous namespace)::$_0::operator()(nnvm::Graph) const::'lambda'(nnvm::TShape const&), std::nullptr_t)::'lambda'(unsigned int, bool)::operator()(unsigned int, bool) const + 2631
[bt] (4) 4   libnnvm_compiler.dylib              0x000000011a67950a std::__1::__function::__func<nnvm::pass::(anonymous namespace)::$_0, std::__1::allocator<nnvm::pass::(anonymous namespace)::$_0>, nnvm::Graph (nnvm::Graph)>::operator()(nnvm::Graph&&) + 4170
[bt] (5) 5   libnnvm_compiler.dylib              0x000000011a65da78 nnvm::ApplyPasses(nnvm::Graph, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) + 1448
[bt] (6) 6   libnnvm_compiler.dylib              0x000000011a64ce16 NNGraphApplyPasses + 566
[bt] (7) 7   libffi.6.dylib                      0x00000001104b8884 ffi_call_unix64 + 76
[bt] (8) 8   ???                                 0x00007ffee046c480 0x0 + 140732661154944

Is the Multiple operator or the Maxpool operator not implemented correctly?
We are calling Maxpool with stride=None, padding=0, dilation=1, ceil_mode=False
We are using Mul with broadcast_i=1, and axis_i = 2 ..is broadcast support for Mul not supported in ONNX? 

Can you help me fix this problem?
thanks a lot, Pallab

**Comment by pallabdatta** [comment]
After little bit of debugging I think its maxpool2d thats mis-intepretting the shape of the input tensor as 6D vs 4D ..so the bug maybe in max_pool2d instead of the Mul..?

**Comment by tqchen** [comment]
close due to inactivity, in the future such general questions can be redirected to https://discuss.tvmlang.org/
