### ISSUE TITLE
how chang mxnet model(.json,.params) to  nnvm model

### ISSUE THREAD

**Issue by zfc929** [dmlc/nnvm#393]
I test  nnvm/tutorials/from_mxnet.py, it is sucess;
but 
1、other mxnet model(.json,.params) , I don‘t know to process us nnvm ,for example ，mxnet/example/image-classification/predict-cpp/image-classification-predict.cc  it us mxnet Inception-BN-symbol.json and Inception-BN-0126.params ，How to apply it to nnvm-tvm.
2、FACE-MTCNN model ,How to apply it to nnvm-tvm.

**Comment by tqchen** [comment]
http://nnvm.tvmlang.org/api/python/frontend.html#nnvm.frontend.from_mxnet 

from_mxnet is generic and you can pass in mxnet symbol and params. We do need the operators to be supported by the nnvm though
