### ISSUE TITLE
Check failed: storage_id >= 0 (-1 vs. 0) Do not support runtime shape op

### ISSUE THREAD

**Issue by zhangxinqian** [dmlc/nnvm#397]
Hi,
I get an error "Check failed: storage_id >= 0 (-1 vs. 0) Do not support runtime shape op" when deploying nnvm model using C++ API with newest version of libtvm_runtime.so. The source codes are in https://github.com/zhangxinqian/example-of-nnvm-in-cpp/blob/master/cpp_deploy.cc. When it runs to this line "tvm::runtime::Module mod = (*tvm::runtime::Registry::Get("tvm.graph_runtime.create"))(json_data, mod_syslib, device_type, device_id);", the error occurs, which is:
"
terminate called after throwing an instance of 'dmlc::Error'
  what():  [04:23:03] src/runtime/graph/graph_runtime.cc:485: Check failed: storage_id >= 0 (-1 vs. 0) Do not support runtime shape op
Stack trace returned 10 entries:
[bt] (0) ./resnet18_v1_dynamic(_ZN4dmlc10StackTraceB5cxx11Ev+0x54) [0x403dd1]
[bt] (1) ./resnet18_v1_dynamic(_ZN4dmlc15LogMessageFatalD1Ev+0x2a) [0x4040b8]
[bt] (2) ../nnvm/tvm/lib/libtvm_runtime.so(_ZN3tvm7runtime12GraphRuntime12SetupStorageEv+0x929) [0x7efeaf0c6279]
[bt] (3) ../nnvm/tvm/lib/libtvm_runtime.so(_ZN3tvm7runtime18GraphRuntimeCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_6ModuleEii+0x2fb) [0x7efeaf0c74bb]
[bt] (4) ../nnvm/tvm/lib/libtvm_runtime.so(+0x928bc) [0x7efeaf0c78bc]
[bt] (5) ./resnet18_v1_dynamic() [0x404cc8]
[bt] (6) ./resnet18_v1_dynamic() [0x404f10]
[bt] (7) ./resnet18_v1_dynamic() [0x402f2d]
[bt] (8) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7efeae6f3830]
[bt] (9) ./resnet18_v1_dynamic() [0x402a59]
"
But the codes work well with old version of libtvm_runtime.so. Then I check file "src/runtime/graph/graph_runtime.cc" and  find the difference in function "void GraphRuntime::SetupStorage()" between two versions. Code changes can be seen in https://github.com/dmlc/tvm/commit/6287a99b9c65ae3a2453047a69d5db73838bd932#diff-5243f3909dfa484d85d3d8471f259169. 
Is it a bug or my fault? 
Thanks.

**Comment by tqchen** [comment]
please update your nnvm to the latest version in the master

**Comment by zhangxinqian** [comment]
@tqchen Still can't work.

**Comment by yidawang** [comment]
I also encountered this error recently. Updating both TVM and NNVM to the latest version fixed it (see [here](https://github.com/dmlc/tvm/issues/995). You may want to double check the version and perhaps re-make both.

**Comment by zhangxinqian** [comment]
@tqchen @yidawang Thanks for your help. I'v solved the problem by re-generating graph json file, lib model and parameters using the latest nnvm. Because my model was generated by old version of nnvm, it could not work with the latest tvm.
