### ISSUE TITLE
Dropout in keras model triggers AssertionError on conversion

### ISSUE THREAD

**Issue by Mofef** [dmlc/nnvm#398]
Line causing error:
```sym, params = nnvm.frontend.from_keras(classifier)```

Top of stack:
```
nnvm-0.8.0-py2.7.egg/nnvm/frontend/common.pyc in set_var(self, name, sym)
    162 
    163     def set_var(self, name, sym):
--> 164         assert isinstance(sym, _sym.Symbol)
    165         self.vars[name] = sym
    166 

AssertionError: 
```
As far as I can see, this is caused by [nnvm.frontend.keras._convert_dense](https://github.com/dmlc/nnvm/blob/master/python/nnvm/frontend/keras.py#L356) returning `None` (instead of `insym` ?)
See debug output below:
```
ipdb> u
> /home/muenst/catkin_ws/src/tf_env/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/frontend/keras.py(446)keras_op_to_nnvm()
    444         raise NotImplementedError("{} is not supported".format((type(keras_layer).__name__)))
    445     ret = _convert_map[type(keras_layer).__name__](insym, keras_layer, symtab)
--> 446     symtab.set_var(outname, ret)
    447 
    448 
ipdb> ret
ipdb> type(ret)
<type 'NoneType'>
ipdb> type(keras_layer).__name__
'Dropout'
ipdb> _convert_map[type(keras_layer).__name__]
<function _default_skip at 0x7f3a460a2c08>
ipdb> _convert_map[type(keras_layer).__name__](insym, keras_layer, symtab)
# None
```
Btw, are you sure, that dropout can just be skipped? During inference it should act as an element wise multiplication by the dropout probability (if this is not accounted for elsewhere, e.g. down-scaled weights).
Related https://github.com/dmlc/tvm/issues/814

**Comment by Huyuwei** [comment]
@Mofef Thanks for reporting. Can you try #399  to see if it fixes the issue?

**Comment by Mofef** [comment]
Cool, thanks for the quick reaction. :)
Looks good to me, at least I run into another issue now. I might open a ticket for this one shortly...

Did you also see my comment in the last paragraph? Are you sure that completely skipping Dropout is correct?

**Comment by Huyuwei** [comment]
I think we can skip dropout in inference. This may be helpful: https://github.com/keras-team/keras/issues/3305

**Comment by Mofef** [comment]
I see, thanks!
