### ISSUE TITLE
[OP] Support dilation in conv2d

### ISSUE THREAD

**Issue by sgxu** [dmlc/nnvm#402]
FILE nnvm/python/nnvm/top/nn.py, in compute_conv2d.
assert dilation == (1, 1), "not support dilate now" .
But if use cudnn, nnvm can support dilation > 1 ?

**Comment by tqchen** [comment]
related https://github.com/dmlc/tvm/pull/316

**Comment by nishi-t** [comment]
I added a PR #439 for the fix.

**Comment by tqchen** [comment]
@Huyuwei can you confirm this? I am only a bit worried the conv2d schedule currently cannot handle the case where dilate is used, we need to confirm that before merge it in

**Comment by Huyuwei** [comment]
It's true that conv2d cuda schedule cannot handle the dilated case. I did a test locally and cuda schedule failed, only llvm passed.

conv2d_transpose also has a dilation stage, it handles dilation by adding ``s[DilatedInput].compute_line()``
https://github.com/dmlc/tvm/blob/master/topi/python/topi/cuda/conv2d_transpose_nchw.py#L88

**Comment by nishi-t** [comment]
@tqchen, @Huyuwei Sorry, I did a test on only llvm. I also confirmed that it doesn't run on cuda with following error.

`ValueError: Direct host side access to device memory is detected in fuse_conv2d. Did you forget to bind?`

Is the cause of this that `topi.nn.dilate` doesn't support cuda? I locally did following code and got same error.

```
import tvm
import numpy as np
import topi

data = tvm.placeholder(shape=(3,3), name="data", dtype="float32")
dilated_data = topi.nn.dilate(data, [2,2])
schedule = tvm.create_schedule(dilated_data.op)
input_np = np.ones((3,3)).astype(data.dtype)
ctx = tvm.gpu(0)
input_tvm = tvm.nd.array(input_np, ctx=ctx)
output_size = topi.util.get_const_tuple(dilated_data.shape)
output_tvm = tvm.nd.array(np.zeros(shape=output_size).astype(dilated_data.dtype), ctx=ctx)
f = tvm.build(schedule, [data, dilated_data], 'cuda')
```

Please tell me if I can cooperate in any way. 
Thnaks

**Comment by tqchen** [comment]
It would be nice if dilation is automatically handled by schedule_conv2d since this seems to be as typical as pad, @Huyuwei do you think if we can update topi schedule to do that?

**Comment by Huyuwei** [comment]
@tqchen Sure, it won't be difficult. I can do it within this week.
@nishi-t You can also try it. The conv schedule should be modified to compute dilated_filter inline when dilated_filter is detected. You can refer to the conv2d_transpose schedule, it computes dilated_input inline.

**Comment by nishi-t** [comment]
@tqchen @Huyuwei Thanks for your comments. I'm going to try it.
