### ISSUE TITLE
is there any docs about register_pattern, register_compute, register_schedule?

### ISSUE THREAD

**Issue by janboeye** [dmlc/nnvm#403]
hi, 

Is there any docs about pattern, compute and schedule for help developers to understand the design?

Thanks

**Comment by kevinthesun** [comment]
They are packed functions which allows user to define operator attribute("TOpPattern", "FTVMCompute", "FTVMSchedule") in python. 

Some basic concepts about packed func: http://docs.tvmlang.org/dev/runtime.html#packedfunc
It would be better if we have more documentations about this part.

**Comment by janboeye** [comment]
@kevinthesun 
what's the relationship about leaky_relu in python/nnvm/top/nn.py and leaky_relu in tvm/topi/python/topi/nn/elemwise.py?
Thanks

**Comment by kevinthesun** [comment]
Operator implementation(how to do actual computation) is defined in tvm. Operator prototype, such as number of inputs/outputs and parameters, is defined in nnvm. To compile the whole graph, we need to register compute(implementation) and schedule(strategy to optimize) for each operator in nnvm. This is done by register_compute and register_schedule. These two functions add "FTVMCompute" and "FTVMSchedule" attributes to operator to call the implementation function in tvm. 

Actually these register can be directly done in C++: https://github.com/dmlc/nnvm/blob/master/src/top/nn/nn.cc#L391
With python, it would be easier if you want to customize compute or schedule for your operator.

**Comment by janboeye** [comment]
@kevinthesun 
leaky_relu in tvm/topi/python/topi/nn/elemwise.py is decorated by tvm.tag_scope, and leaky_relu in src/top/nn/nn.cc#L391 is also for compute, what's the difference between these two leaky_relu implementation?

Thanks

**Comment by kevinthesun** [comment]
https://github.com/dmlc/nnvm/blob/master/src/top/nn/nn.cc#L391 uses cpp implementation of leaky_relu in tvm, while leaky_relu in tvm/topi/python/topi/nn/elemwise.py is python implementation. They are equal in terms of functionality. In the long term, operators in tvm will be implemented in cpp so that they can be exposed by various languages.

**Comment by tqchen** [comment]
let us move general discussion to https://discuss.tvmlang.org/
