### ISSUE TITLE
about vthread

### ISSUE THREAD

**Issue by janboeye** [dmlc/nnvm#407]
thread_xz = tvm.thread_axis((0, vthread), "vthread", name="vx")
tyz, fi = s[B].split(fi, nparts=vthread)  # virtual thread split
s[B].bind(tyz, thread_yz)

How is vthread mapped to threadIdx?

Thanks

**Comment by yidawang** [comment]
@Laurawly ?

**Comment by janboeye** [comment]
why not use bind(tyz, thread_z) instead of vthread?
@Laurawly 

Thanks

**Comment by tqchen** [comment]
We are moving the question and discussion issues to [TVM Discuss forum](https://discuss.tvmlang.org) and only use issue tracker for development purposes. Please create a post there :)
