### ISSUE TITLE
Dynamic graphs with NNVM

### ISSUE THREAD

**Issue by alex-weaver** [dmlc/nnvm#409]
What is NNVM's story for handling dynamic graphs? Is the intention for NNVM to handle everything between branches (effectively the basic blocks of the computation) and leave the branching behaviour to the client? Or is it intended that NNVM will handle branching/looping within the graph?

**Comment by tqchen** [comment]
We are moving the question and discussion issues to [TVM Discuss forum](https://discuss.tvmlang.org) and only use issue tracker for development purposes. Please create a post there :)
