### ISSUE TITLE
what does support level do? how to decide them?

### ISSUE THREAD

**Issue by fumihwh** [dmlc/nnvm#412]
I find `Op` has `support_level` field and can't figure out what does it do.
Could anyone help?

**Comment by fumihwh** [comment]
I found them in docs. So support level shows op's type.
```
Level 1: Basic Operators
Level 2: Convolutions
Level 3: Additional Tensor Ops
Level 4: Broadcast and Reductions
```
Why we categorise ops into such 4 levels?
What the difference between basic ops and additional tensor ops?

I saw `nnvm.symbol.leaky_relu` is an `additional tensor op`, mean time, `nnvm.symbol.relu` is basic op.
So I guess `additional tensor op` is a variant of `basic op`.
But I saw `nnvm.symbol.ones` and `nnvm.symbol.ones_like` both are basic ops.
Also `nnvm.symbol.full` and `nnvm.symbol.full_like` etc,.
A counter-example is `nnvm.symbol.expand_dims` and `nnvm.symbol.expand_like`.
`nnvm.symbol.expand_dims` is basic op, `nnvm.symbol.expand_like` is `additional tensor op`.

So I confused, how to decide which op is basic which is additional?

**Comment by tqchen** [comment]
support level is mainly used to determine the prioritization of ops to get a minimum running version that support small set of ops and meaningful applications. It has nothing to do with the  implementation. First three level are minimum set that enables typical convnets

**Comment by fumihwh** [comment]
@tqchen 
So if one wants to add an op, how to tell which level should it belong to? 
If can not give a clearly reason, I think there four levels are too loose. 

Again, why `nnvm.symbol.ones` and `nnvm.symbol.ones_like` are both basic ops,
but `nnvm.symbol.expand_dims` is basic op and  `nnvm.symbol.expand_like` is additional tensor op?

**Comment by tqchen** [comment]
By default, the support level should set to additional initially. expand_like is a non-conventional op(because it is not in numpy)

**Comment by fumihwh** [comment]
@tqchen 
Thanks, now make sense.

If I understand correctly,
in numpy: level 1 or level 2 (depends on if Convolutions relative)
not in numpy: level 3
Broadcast and Reductions: level 4

**Comment by tqchen** [comment]
necessary to give me say resnet, vgg and in numpy level 1
not in numpy: level 5

**Comment by fumihwh** [comment]
So there are 5 levels? 

resnet, vgg and in numpy: level 1
resnet, vgg and in numpy and conv relative: level 2
resnet, vgg but not in numpy: level 3 (`expand_like`)
Broadcast and Reductions: level 4
not resnet, vgg and not in numpy: level 5

Are Target nets resnet and vgg only?

**Comment by tqchen** [comment]
we cannot say they are resnet/vgg, they should include typical cnn models only but we could use our own judgement on this. Support level provides a rough characteristics of urgency of supporting things

**Comment by fumihwh** [comment]
@tqchen Thanks
