### ISSUE TITLE
version control

### ISSUE THREAD

**Issue by fumihwh** [dmlc/nnvm#414]
Actually, I am working around onnx, onnx-tensorflow.
Onnx has version control and will make break change sometimes.
So, how does nnvm deal with such situation?
And, is there any folk maintaining onnx frontend? If isn't, I will maintain it.

**Comment by tqchen** [comment]
We should keep up to date support with onnx up to last version, contribution is always welcomed

**Comment by fumihwh** [comment]
@tqchen 
BTW, support all version of onnx is a better idea, of course last version has priority.

**Comment by tqchen** [comment]
sure, take backward compatibility up to 1.0 is good

**Comment by fumihwh** [comment]
@tqchen 
onnx's version control is a little bit complex.
They have at least 3 kind of version. ir version, opset version, onnx version (maybe more).
Opset version known as operator version. https://github.com/onnx/onnx/blob/master/docs/Versioning.md#operator-versioning
Frontend compatibility should be concerned due to different opset versions has different specifications. 
opset version is more meaningful than onnx version.
What do you think?
