### ISSUE TITLE
Pass-through FTVMCompute requires topi::identity

### ISSUE THREAD

**Issue by nhynes** [dmlc/nnvm#425]
The following is impossible to schedule
```c++
FTVMCompute(attrs, inputs, _) {
    return Array<Tensor>{ inputs[0] };
}
```
whereas the following works
```c++
FTVMCompute(attrs, inputs, _) {
    return Array<Tensor>{ topi::identity(inputs[0]) };
}
```

While the technical details of TVM likely require such an operation (which hopefully gets simplified out), the API is unintuitive and the resulting error is particularly challenging to debug.  It might be worth looking into this so that future end-users are able to develop custom operators.

**Comment by tqchen** [comment]
good point, maybe a verifier in build can be used to generate a more friendly error message

**Comment by nhynes** [comment]
Heh, if we're on the topic of error messages, don't even get me started on the asserts in `arg_binder.cc`. All are things on my to-do list, however!

**Comment by tqchen** [comment]
close this for now, move general discussion to https://discuss.tvmlang.org/ so issue tracker only contains things that can are actionable, we can open a new issue to track if there are specific proposals
