### ISSUE TITLE
[FRONTEND][ONNX] Attribute based weight Initialization

### ISSUE THREAD

**Issue by hstox** [dmlc/nnvm#433]
Hi,

I'm trying to import ONNX models from CNTK-2.5 into nnvm. Even the simplest 1 layer network throws an exception "NotImplementedError: Filed t is not supported in nnvm" on

onnx_model = onnx.load('test.onnx')
sym, params = nnvm.frontend.from_onnx(onnx_model)

When trying to find a solution/work-around, I found the following CNTK issue, https://github.com/Microsoft/CNTK/issues/2825, mentioning that CNTK does not store its values in initializers, but in attributes. Apparently the ONNX standard allows both methods.

Is this the reason for the import failure? If so, can you recommend a workaround and/or conversion tool to import CNTK ONNX models into nnvm?

Thanks in advance for your help.

-Harry

**Comment by fumihwh** [comment]
Try put Field `t`'s value in `attrs[a.name]`.

**Comment by tqchen** [comment]
if it is an actionable item, please open an issue in TVM repo
