### ISSUE TITLE
Performance of Resnet50 is much slower than Tensorflow on Intel i7 of Mac

### ISSUE THREAD

**Issue by FrozenGene** [dmlc/nnvm#440]
I follow the https://github.com/dmlc/nnvm/blob/master/examples/benchmark/gpu_imagenet_bench.py, I modify the target to "llvm -mcpu=core-avx2".

The model of VGG16 / mobilenet is faster than tensorflow. VGG16 is 141ms, mobilenet is 12.5ms, tensorflow's VGG16 is 274.434 ms and mobilenet is 56.511. **However for the model Resnet50, TVM is 339ms, but tensorflow is 138.267ms.** Does the TVM not optimize the Resnet50 on the Intel i7 CPU? Thanks.

**Comment by yidawang** [comment]
Recently we are doing some optimization work more focusing on Intel Xeon. See https://github.com/dmlc/tvm/pull/883 as an example. We believe most of our scheduling schemes could be applied to Intel Core. Stay tuned.

Also, you are welcome to redirect your questions to https://discuss.tvmlang.org/ in the future.

**Comment by FrozenGene** [comment]
Right. I have set the mcpu to avx2, without it, TVM is slower. But from the view of mine, this key issue should be TVM has not done schedule for Resnet50, only for Resnet18. See https://github.com/dmlc/tvm/blob/8ef4fdef229fcce37f9c71bd4b916811471fea9d/topi/python/topi/x86/conv2d.py#L35

If it is not right, please correct me.

**Comment by yidawang** [comment]
We also have Resnet50 along with a lot of other networks optimized for Intel CPUs. We will release the code and benchmarking results later. @yzhliu @kevinthesun can give you more details.

In addition, TF does not perform well on Intel CPUs in general. It is better to use MXNet with MKLDNN enabled as the baseline.

**Comment by yzhliu** [comment]
we just haven't contribute the schedules back to tvm. sorry for the inconvenience. will make a PR in a couple of days.

**Comment by FrozenGene** [comment]
> we just haven't contribute the schedules back to tvm. sorry for the inconvenience. will make a PR in a couple of days.

@yzhliu I am glad to hear that. I go through your code repository, I don't find related changeset of schedule code. Because I am investigating the performance of TVM, could I use the code of your PR to test? I am caring about Resnet50's performace. Currently, if I close loop-unroll, TVM's Resnet50 will be about 800~900ms, if turn on, will be about 339ms. I think if TVM has schedule of Resnet50, it will have better performance than tensorflow.

**Comment by FrozenGene** [comment]
@kevinthesun Thanks. Glad to hear this news!

**Comment by yzhliu** [comment]
@FrozenGene well, if you want to quickly test resnet-50, here's the missing schedules and workloads (just grabbed them out from my shitty code, it should work) :

schedules:
```
# workloads of resnet50_v1 on imagenet
AVXConv1x1Fwd(16, fp32_vec_len, 2, 28),
AVXConv1x1Fwd(16, fp32_vec_len, 2, 28),
AVXConv1x1Fwd(16, fp32_vec_len, 2, 28),
AVXConv1x1Fwd(16, fp32_vec_len, 2, 28),
AVXConv1x1Fwd(16, fp32_vec_len, 2, 28),
AVXConv1x1Fwd(16, fp32_vec_len, 2, 28),
AVXConv1x1Fwd(16, fp32_vec_len, 2, 14),
AVXConv1x1Fwd(16, fp32_vec_len, 2, 14),
AVXConv1x1Fwd(16, fp32_vec_len, 2, 14),
AVXConv1x1Fwd(16, fp32_vec_len, 2, 14),
AVXConv1x1Fwd(16, fp32_vec_len, 2, 7),
AVXConv1x1Fwd(16, fp32_vec_len, 2, 7),
AVXConv1x1Fwd(16, fp32_vec_len, 2, 7),
AVXConv1x1Fwd(16, fp32_vec_len, 2, 7),
# workloads of resnet50_v2 on imagenet
AVXConvCommonFwd(16, fp32_vec_len, 28, True),
AVXConvCommonFwd(16, fp32_vec_len, 14, False),
AVXConvCommonFwd(16, fp32_vec_len, 7, True),
```

workloads:
```
# workloads of resnet50_v1 on imagenet
Workload('float32', 'float32', 56, 56, 64, 256, 1, 1, 0, 0, 1, 1),
Workload('float32', 'float32', 56, 56, 256, 64, 1, 1, 0, 0, 1, 1),
Workload('float32', 'float32', 56, 56, 256, 128, 1, 1, 0, 0, 2, 2),
Workload('float32', 'float32', 28, 28, 128, 512, 1, 1, 0, 0, 1, 1),
Workload('float32', 'float32', 56, 56, 256, 512, 1, 1, 0, 0, 2, 2),
Workload('float32', 'float32', 28, 28, 512, 128, 1, 1, 0, 0, 1, 1),
Workload('float32', 'float32', 28, 28, 512, 256, 1, 1, 0, 0, 2, 2),
Workload('float32', 'float32', 14, 14, 256, 1024, 1, 1, 0, 0, 1, 1),
Workload('float32', 'float32', 28, 28, 512, 1024, 1, 1, 0, 0, 2, 2),
Workload('float32', 'float32', 14, 14, 1024, 256, 1, 1, 0, 0, 1, 1),
Workload('float32', 'float32', 14, 14, 1024, 512, 1, 1, 0, 0, 2, 2),
Workload('float32', 'float32', 7, 7, 512, 2048, 1, 1, 0, 0, 1, 1),
Workload('float32', 'float32', 14, 14, 1024, 2048, 1, 1, 0, 0, 2, 2),
Workload('float32', 'float32', 7, 7, 2048, 512, 1, 1, 0, 0, 1, 1),
# workloads of resnet50_v2 on imagenet 3 26-28
Workload('float32', 'float32', 56, 56, 128, 128, 3, 3, 1, 1, 2, 2),
Workload('float32', 'float32', 28, 28, 256, 256, 3, 3, 1, 1, 2, 2),
Workload('float32', 'float32', 14, 14, 512, 512, 3, 3, 1, 1, 2, 2),
```

Put them after this line https://github.com/dmlc/tvm/blob/8ef4fdef229fcce37f9c71bd4b916811471fea9d/topi/python/topi/x86/conv2d.py#L59 and this line https://github.com/dmlc/tvm/blob/8ef4fdef229fcce37f9c71bd4b916811471fea9d/topi/python/topi/nn/conv2d.py#L47 respectively.

It should enable you to run ResNet-152 as well. Have fun.

As @kevinthesun described, don't be surprised when you see your network become faster in a week or two.

**Comment by FrozenGene** [comment]
@yzhliu Yes, it works. TVM's resnet runtime is 118.12ms using this schedule (config is opt_level 3 / Loop unroll step is 128, llvm -mcpu=core-avx2), which is better than tensorflow now (Tensorflow is 138.627ms). I am investigating the TVM's performance and plan to introduce TVM into my company, I must compare with tensorflow (MXNet + MKLDNN is one plus, but not must), which is one key factor to help me push TVM successfully. If success, our modification of TVM will contribute back to the community. And I am also glad to hear that we have plan to make TVM faster.

**Comment by tqchen** [comment]
Glad to see good discussion here, let us move more discussions to https://discuss.tvmlang.org/

@FrozenGene Your contribution for joining the discussion is more the welcomed, TVM stack itself adopts apache style governance which means its roadmap and future depends on the diverse expertise of its contributors.

**Comment by FrozenGene** [comment]
@tqchen @yzhliu @yidawang @kevinthesun Thanks, everyone. I have pushed NNVM / TVM successfully into one project into my company Alibaba. I must say that our project's scenario is very amazing and will collect VERY MUCH MUCH data, I think it will help TVM better. However, because our trained framework is tensorflow and can not change, we need teach TVM recognize Tensorflow model. I have opened one question about this, if you can give some advice, which will be very nice. https://discuss.tvmlang.org/t/teach-nnvm-recognize-tensorflow-model/82
