### ISSUE TITLE
C++ json format parsing

### ISSUE THREAD

**Issue by dtmoodie** [dmlc/nnvm#454]
I'm trying to load the json graph file from c++ to get the shape information for allocating input and output buffers.  However I'm having trouble parsing the json.

When using dmlc::JSONParser, it appears that it cannot selectively parse the json file.  Using https://github.com/dmlc/tvm/blob/master/src/runtime/graph/graph_runtime.cc as an example, I do the following:

    std::ifstream json_in(model_file.string(), std::ios::in);
    dmlc::JSONReader reader(&json_in);
    reader.BeginObject();
    std::string key;
    while(reader.NextObjectItem(&key))
    {
        if(key == "attrs")
        {
                        
        }
    }

This succeed to read the first key "nodes" but throws an error on the next call to NextObjectItem, which seems to indicate that I need to parse the whole json file, which is consistent with the comment "The user need to know the schema".  I'd prefer not to reproduce the entire json file parsing format just to extract a few attributes, so I tried to use cereal to parse the json, this throws errors likely due to cereal requiring a more strict json formatting.  
Does anyone have a suggestion for an easy way to extract the shape attributes?

**Comment by tqchen** [comment]
close this for now as the original questions is answered, further questions are encouraged to be asked at https://discuss.tvmlang.org/
