### ISSUE TITLE
[DOCS] How to update online document?

### ISSUE THREAD

**Issue by liangfu** [dmlc/nnvm#455]
The [on-line document](http://nnvm.tvmlang.org) seems obsolete, many recent changes are not reflected on the document. For instance, many functions like `get_internals` and `get_children` are not listed as class methods in [nnvm.symbol](http://nnvm.tvmlang.org/api/python/symbol.html) . 

I think it's reasonable to specify how to update these on [contribute.md](https://github.com/dmlc/nnvm/blob/master/docs/how_to/contribute.md) .

**Comment by tqchen** [comment]
nice catch, can you do it? 

For that specific problem, we need to change https://github.com/dmlc/nnvm/blob/master/docs/api/python/symbol.rst to add ```:members:``` as in https://raw.githubusercontent.com/dmlc/tvm/master/docs/api/python/module.rst

**Comment by tqchen** [comment]
The document will get updated automatically once the PR is merged in

**Comment by liangfu** [comment]
sure, see PR #456

**Comment by liangfu** [comment]
The document is not updated even after the PR is merged in.
