### ISSUE TITLE
Segmentation fault when running tutorials/get_started.py

### ISSUE THREAD

**Issue by limin2015** [dmlc/nnvm#459]
When I finish installing nnvm (I have successfully installed tvm before, and I can successfully run examples in tutorials/ ), I try to run the example in tutorials/get_started.py. But it failed with the following information:

command: python ./tutorials/get_started.py 

output:
-------compute graph-------
Graph(%x, %y) {
  %2 = sqrt(%y)
  %3 = elemwise_add(%x, %2)
  ret %3
}
Segmentation fault (core dumped)

It seems that this error is caused by calling the function "nnvm.compiler.build" in line 48 in get_started.py. 

Can anyone help me?

**Comment by yzhliu** [comment]
I don't see the problem with the latest nnvm and tvm. maybe try upgrade and reinstall both?

**Comment by tqchen** [comment]
future questions are encouraged at https://discuss.tvmlang.org/
