### ISSUE TITLE
How to deal with case that attr is given as a tensor?

### ISSUE THREAD

**Issue by fumihwh** [dmlc/nnvm#461]
For example, 
```
@tvm.tag_scope(tag=tag.INJECTIVE)
def reshape(a, newshape):
    """Reshape the array

    Parameters
    ----------
    a : tvm.Tensor
        The tensor to be reshaped
    newshape : tuple of ints
        The new shape

    Returns
    -------
    ret : tvm.Tensor
    """
    ndim = len(a.shape)
    a_shape = [a.shape[i] for i in range(ndim)]
    return tvm.compute(newshape,
                       lambda *indices: a(*unravel_index(ravel_index(indices, newshape), a_shape)))
```
if both `input_0` and `input_1` are Tensors, we can't parse `input_1` to `ReshapeParam`, right?
So in this case, we can not run it in nnvm except that `input_1` is included in `graph.initializer`, right?

BTW, I am working on run onnx reshape on nnvm. Following code works well when `input_1` is included in `graph.initializer`.
```
class Reshape(OnnxOpConverter):

    @classmethod
    def _impl_v1(cls, inputs, attr, params):
        return _sym.reshape(inputs[0], shape=attr['shape'])

    @classmethod
    def _impl_v5(cls, inputs, attr, params):
        return _sym.reshape(
            inputs[0],
            shape=tuple(params[inputs[1].list_output_names()[0]].asnumpy()))
```

**Comment by tqchen** [comment]
This is true. for most of the cases of reshape the shape is known ahead of time and that can benefit optimization a lot, @fumihwh your solution looks fine for constant shape and can you send a PR :)?

**Comment by fumihwh** [comment]
@tqchen Thanks.
The code I posted is already in master.
I will raise an error when shape is not param and also not in graph.initializer.
