### ISSUE TITLE
OpenCL segmentation fault on ARM CPUs while using TVM

### ISSUE THREAD

**Issue by dcsgan** [dmlc/nnvm#462]
Hi, 
I installed freeocl to enable opencl in ARM CPUs. I installed nnvm and tvm framework on linux 16.04 (native install on arm). I tried to run the following imagenet example

import time
import argparse
import numpy as np
import tvm
import nnvm.compiler
import nnvm.testing
from tvm.contrib import util, nvcc
from tvm.contrib import graph_runtime as runtime

@tvm.register_func
def tvm_callback_cuda_compile(code):
    ptx = nvcc.compile_cuda(code, target="ptx")
    return ptx

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model', type=str, required=True, choices=['resnet', 'mobilenet', 'vgg'],
                        help="The model type.")
    parser.add_argument('--opt-level', type=int, default=3,
                        help="Level of optimization.")
    parser.add_argument('--num-iter', type=int, default=100,
                        help="Number of iteration during benchmark.")
    args = parser.parse_args()
    opt_level = args.opt_level
    num_iter = args.num_iter
    target = "opencl"
    ctx = tvm.cl(0)
    batch_size = 1
    num_classes = 1000
    image_shape = (3, 224, 224)

    data_shape = (batch_size,) + image_shape
    out_shape = (batch_size, num_classes)
    if args.model == 'resnet':
        net, params = nnvm.testing.resnet.get_workload(
            batch_size=batch_size, image_shape=image_shape)
    elif args.model == 'mobilenet':
        net, params = nnvm.testing.mobilenet.get_workload(
            batch_size=batch_size, image_shape=image_shape)
    elif args.model == 'vgg':
        net, params = nnvm.testing.vgg.get_workload(
            batch_size=batch_size, image_shape=image_shape, num_layers=19, batch_norm=True)
    else:
        raise ValueError('no benchmark prepared for {}.'.format(args.model))

    with nnvm.compiler.build_config(opt_level=opt_level):
        with tvm.build_config(auto_unroll_max_step=32,
                              auto_unroll_min_depth=0,
                              unroll_explicit=False):
            graph, lib, params = nnvm.compiler.build(
                net, target, shape={"data": data_shape}, params=params)

    data = np.random.uniform(-1, 1, size=data_shape).astype("float32")
    np.save("input.npz", data)
    module = runtime.create(graph, lib, ctx)
    module.set_input(**params)
    module.set_input("data", data)
    module.run()
    out = module.get_output(0, tvm.nd.empty(out_shape))
    np.save("output.npz", out.asnumpy())

    print('benchmark args: {}'.format(args))
    ftimer = module.module.time_evaluator("run", ctx, num_iter)
    for i in range(3):
        prof_res = ftimer()
        print(prof_res)
        # sleep for avoiding cpu overheat
        time.sleep(20)

if __name__ == '__main__':
    main()

Output of my gdb debug session

[05:41:39] src/runtime/opencl/opencl_device_api.cc:210: Multiple OpenCL platforms matched, use the first one ... 
[05:41:39] src/runtime/opencl/opencl_device_api.cc:211:  Not using first but second ...
[05:41:39] src/runtime/opencl/opencl_device_api.cc:215: Initialize OpenCL platform 'FreeOCL'
[05:41:39] src/runtime/opencl/opencl_device_api.cc:220: No OpenCL device any device matched given the options: gpu mode
[05:41:39] src/runtime/opencl/opencl_device_api.cc:221: Now try OpenCL cpu mode
[05:41:39] src/runtime/opencl/opencl_device_api.cc:240: opencl(0)='ARMv7 Processor rev 3 (v7l)' cl_device_id=0xa5be6ba0
[New Thread 0x9d826470 (LWP 7992)]
1604566744ns
[New Thread 0x9d026470 (LWP 7999)]
[New Thread 0x9c514470 (LWP 8000)]
[New Thread 0x9abfe470 (LWP 8001)]
[New Thread 0x9a3fe470 (LWP 8002)]
[New Thread 0x992fe470 (LWP 8003)]
[New Thread 0x981fe470 (LWP 8004)]
[New Thread 0x970fe470 (LWP 8005)]

Thread 29 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x9d026470 (LWP 7999)]
0xa6f45de6 in fuse_conv2d_broadcast_add_relu_6__kernel0 (input0=<optimized out>, pad_temp=<optimized out>)
    at /tmp/file1oomAV:792
792	(pad_temp [(((((((__int )get_group_id(0 )) * 256 ) + ((__int )get_local_id(0 ))) / 3136 ) * 3136 ) + ((((((((__int )get_group_id(0 )) * 256 ) + ((__int )get_local_id(0 ))) / 56 ) % 56 ) * 56 ) + (((((__int )get_group_id(0 )) * 32 ) + ((__int )get_local_id(0 ))) % 56 )))] = input0 [(((((((__int )get_group_id(0 )) * 256 ) + ((__int )get_local_id(0 ))) / 3136 ) * 3136 ) + ((((((((__int )get_group_id(0 )) * 256 ) + ((__int )get_local_id(0 ))) / 56 ) % 56 ) * 56 ) + (((((__int )get_group_id(0 )) * 32 ) + ((__int )get_local_id(0 ))) % 56 )))]);

**Comment by tqchen** [comment]
c.f. #518 we will redirect further developments to tvm repo
