### ISSUE TITLE
Bug: nnvm.compile.build fails with nightly

### ISSUE THREAD

**Issue by ehsanmok** [dmlc/nnvm#470]
## UPDATE

This is definitely a bug. I revert NNVM back to 8cb4785e84a1be2ca2c749fc22cd7806561dd9b3 and the build are successful!
----------------------------------------
Hi

I was successfully `nnvm.compile.build`ing for cuda, opencl and I just built the tvm and nnvm (nightly) from source and all of my previous builds have failed with `opt_level=2`

```
ValueError: Direct host side access to device memory is detected in fuse_conv2d_broadcast_mul_broadcast_add_relu. Did you forget to bind?
```
With `opt_level=0` I get 

```
ValueError: Direct host side access to device memory is detected in fuse_conv2d. Did you forget to bind?
```
Complete error logs:

```
 File "/home/ilab/anaconda3/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/build_module.py", line 290, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/home/ilab/anaconda3/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/home/ilab/anaconda3/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/_base.py", line 75, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "tvm/_ffi/_cython/./function.pxi", line 38, in core.tvm_callback
  File "/home/ilab/anaconda3/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/build_module.py", line 123, in _build
    return tvm.build(funcs, target=target, target_host=target_host)
  File "/home/ilab/anaconda3/lib/python3.6/site-packages/tvm-0.2.0-py3.6-linux-x86_64.egg/tvm/build_module.py", line 452, in build
    "Did you forget to bind?" % func.name)
ValueError: Direct host side access to device memory is detected in fuse_conv2d. Did you forget to bind?

```

Though for target llvm is working fine!

**Comment by merrymercy** [comment]
Possible cause is the recent change in dilation #439. If you do not inline dilation, there will be a stage without thread binding. Then it comes the error message you report.

But I think https://github.com/dmlc/tvm/pull/1129 have fixed this problem already.

Do you use custom schedule? Can you check whether the convolution schedule in your code has following lines
https://github.com/Huyuwei/tvm/blob/5a5bdd6e9516da76e57a80b913402bcc1411ae47/topi/python/topi/cuda/conv2d_nchw.py#L498-L499

**Comment by ehsanmok** [comment]
@merrymercy afaik no custom schedule. Even the simple resnet compilation was failing for me.

**Comment by merrymercy** [comment]
Can you undo the changes in #439 manually  (about 10 lines) and see whether the error is fixed?

**Comment by ehsanmok** [comment]
@merrymercy I'd like to but have no time now.

**Comment by nishi-t** [comment]
Hi, @ehsanmok 
Did you build and install newer tvm than dmlc/tvm#1129 merged [commit](https://github.com/dmlc/tvm/commit/d1cf60751e9d5034cee810a3646d87935e622a65) ? It might be good to check tvm version and reinstall it.

**Comment by tqchen** [comment]
see if https://github.com/dmlc/nnvm/pull/477 fixed the case

**Comment by ehsanmok** [comment]
@tqchen yes, thanks you, compilation works now!
