### ISSUE TITLE
relu6 not implemented

### ISSUE THREAD

**Issue by k-zhou08** [dmlc/nnvm#473]
when I use the nnvm to build the mobilenet_1_0_224_tf.h5   model, error occurs:
     raise NotImplementedError('relu6 not implemented')
     NotImplementedError: relu6 not implemented

PS:   ResNet50 could be successfully  build

**Comment by tqchen** [comment]
please redirect general questions to https://discuss.tvmlang.org/. Also specify which frontend you are using. It should be as simple as patch up the front end to support relu6, by redirecting that to clip

**Comment by k-zhou08** [comment]
the frontend is Keras, I am sorry for forgetting mention that. and I tried the " https://discuss.tvmlang.org/" website and It seems that I was not authorized to start a new topic .

**Comment by tqchen** [comment]
you should be able to login with your github account to start a new topic

**Comment by k-zhou08** [comment]
yeah, I login in with my github account.

**Comment by k-zhou08** [comment]
OK , Done , it turns out that the browser problem, I have created the topic, looking forward to your response.
