### ISSUE TITLE
[OP] Add slice operator

### ISSUE THREAD

**Issue by tqchen** [dmlc/nnvm#488]
To support advanced indexing. c.f. https://mxnet.incubator.apache.org/api/python/ndarray/ndarray.html?highlight=slice#mxnet.ndarray.slice

Also need support in TOPI

**Comment by srkreddy1238** [comment]
Helps Slice & Strided Slice of tensorflow :)

**Comment by PariksheetPinjari909** [comment]
This I have already implemented, will raise PR soon...

**Comment by tqchen** [comment]
move to https://github.com/dmlc/tvm/issues/1183
