### ISSUE TITLE
[Graph, Shape of Node] How to get the shape of each node?

### ISSUE THREAD

**Issue by troore** [dmlc/nnvm#496]
Hi,

I've located that the two parts of a NNVM graph:

1. The computation graph structure
2. The attribute map

For each node of the graph, I could get the filter information through the 'attrs' member of Node, including filter size, number of channels, etc. I could also get the input shapes of all nodes from the attribute map mentioned above. However, how could I get the shape for a given node, like the way I get the filter information (have a connection of the attribute map with nodes in a graph)?

Thanks,
troore

**Comment by srkreddy1238** [comment]
Not sure I understood correctly..

NNVM graph definition is JSON file which contains shape of each node.

Can you give context for this ?

I think this could move to discussion forum.
discuss.tvmlang.org

**Comment by troore** [comment]
@srkreddy1238 Thanks for your reminding. Let me explain my scenario before move it to the forum. The shape I mean is actually the input image shape, say, during image classification.
