### ISSUE TITLE
symbol.cast has no FTVMCompute

### ISSUE THREAD

**Issue by FrozenGene** [dmlc/nnvm#516]
If we use symbol.cast for sym, it will report ```Check failed: idx < data_.size() && data_[idx].second Attribute FTVMCompute has not been registered for Operator cast```

**Comment by srkreddy1238** [comment]
Ref. https://github.com/dmlc/nnvm/pull/472

I have exposed cast to nnvm front end as part of above PR.

**Comment by tqchen** [comment]
c.f. #518 we will redirect further changes to tvm repo, we can open a new issue there
