### ISSUE TITLE
use nnvm compiler in c runtime without python

### ISSUE THREAD

**Issue by souptc** [dmlc/nnvm#517]
I am planning to use nnvm compiler and tvm to run some graph from other framework (keras and onnx), but it seems nnvm compiler rely on the functions registried from python, but I don't plan to depends on python. Is there any solution that could use it without its python package?

**Comment by ehsanmok** [comment]
Have you checked the c++ option [here]?(https://github.com/dmlc/nnvm/blob/master/docs/how_to/deploy.md).

**Comment by souptc** [comment]
So I need to compile the graph offline with nnvm compiler python package,
then deploy the execution graph to tvm runtime? How to generate the "tvm
module library of compiled functions"?

2018-05-26 16:06 GMT-07:00 Ehsan M. Kermani <notifications@github.com>:

**Comment by ehsanmok** [comment]
@souptc Oops! sorry I deleted my comment. If your ops have already been supported by any of `from_keras` or `from_onnx` etc, you can use either of backends C++/Python to generate graph, lib and params then load and create graph runtime using any of frontend APIs, C++/Python/Java/JavaScript (for now).

If there're ops that aren't supported either you can use topi (in tvm) or tvm itself to generate a single .so and load it at runtime. New [tvm guid](http://docs.tvmlang.org/tutorials/get_started.html#sphx-glr-tutorials-get-started-py) shows it clearly.

**Comment by souptc** [comment]
thanks for the response @ehsanmok , so basically to take advantage of nnvm compiler to generate graph / compiled function, I need to use Python (from_keras/onnx and topi are both python apis), right?

**Comment by ehsanmok** [comment]
Yes, based on what you first wrote that you have keras/onnx models, then Python is the way to go.

**Comment by souptc** [comment]
thanks.
