### ISSUE TITLE
Issue in importing tensorflow graph def to NNVM 

### ISSUE THREAD

**Issue by iamsarbartha** [dmlc/nnvm#524]
Hi,
    Whenever I run the from_tensorflow.py in tutorial, I get the following error 
![screen shot 2018-09-05 at 7 41 04 am](https://user-images.githubusercontent.com/23423020/45093804-3056f180-b0df-11e8-979a-cab2f63314cd.png)

Can you please shed some light on this issue. The dtype is uint8 in the example.

**Comment by tqchen** [comment]
please use https://discuss.tvm.ai/ for general discussions, the repo is moved as part of https://github.com/dmlc/tvm/
