### ISSUE TITLE
Confusing `num_inputs` interface of node

### ISSUE THREAD

**Issue by jermainewang** [dmlc/nnvm#63]
I found following two ways of extracting number of inputs quite confusing.

``` c++
Node* node = ...;
node->inputs.size();
node->num_inputs();
```

And most importantly, sometimes **they are different**! So what exactly are the meanings of these two? Can we change the name of it?

**Comment by tqchen** [comment]
They should always be the same in theory, except for the variable length input case.
 
node->num_inputs() is short cut for node->op()->num_inputs(), it is used to decide number of inputs before the graph composition. Any proposals?

**Comment by jermainewang** [comment]
Hmm, I sometimes find node->num_inputs() will return uninitialized value.

**Comment by jermainewang** [comment]
How about `num_inputs_required()` ? Because this function basically returns the number of inputs required by the underlying operator. While `node->inputs.size()` is the information of graph connectivity. I found the case where they are different may be because the attribute is not being parsed. For example,
```c++
NodePtr node = Node::Create();
node->op = Op::Get("ElewiseSum");
node->attrs.dict["num_args"] = std::to_string(4);
cout << node->num_inputs() << endl;
```
Note that the above result will be undefined since `node->attrs.op->attr_parser(&(node->attrs))` is not called. I think a better way to prevent this happens and make everything more well-defined is to have a NodeBuilder in NNVM.
```c++
NodePtr node = NodeBuilder::Get()
   .SetOp(Op::Get("ElewiseSum"))
   .SetAttrs("num_args", std::to_string(4));
cout << node->num_inputs() << endl;
```
The destructor of NodeBuilder will call proper attribute parser thus preventing any crappy intermediate state.

**Comment by jermainewang** [comment]
Suddenly realized that such NodeBuilder is just `nnvm::Symbol`. Can we use `nnvm::Symbol` when writing Pass function?
