### ISSUE TITLE
Graph passes not showing as registered in libnnvm.a

### ISSUE THREAD

**Issue by slayton58** [dmlc/nnvm#64]
If I link against libnnvm.a in my application, no passes are shown as registered. If I explicitly compile in (fir instance) $(NNVM_ROOT)/build/pass/saveload_json.o I have access to the LoadJSON and SaveJSON passes.

Is this expected behavior?

**Comment by tqchen** [comment]
Will need to link the library via --whole-archive,  c.f. https://github.com/dmlc/nnvm/blob/master/Makefile#L41

**Comment by slayton58** [comment]
Perfect, thanks!

**Comment by tqchen** [comment]
have fun

**Comment by slayton58** [comment]
@tqchen I have other questions about using NNVM - would you prefer I open issues each time to keep everything public, or if you're willing we could email as well (I sent one last night to your .edu address)

**Comment by tqchen** [comment]
@slayton58 Interesting, I checked my inbox and didn't find the email. Maybe you could try send  another one.

**Comment by slayton58** [comment]
@tqchen I just sent another one from my nvidia address, subject "NNVM C API"

**Comment by tqchen** [comment]
Still not get it. Make sure it is tqchen at cs dot washington

**Comment by slayton58** [comment]
I used tqchen at cs dot washington dot edu (just tried with my personal email too)
