### ISSUE TITLE
Typing of grad_xs, grad_ys, grad_ys_out_grad attributes

### ISSUE THREAD

**Issue by slayton58** [dmlc/nnvm#66]
What exactly should these types be? The tinyflow gradient generator seems to suggest symbol groups, but is that the case?

Then, with the C++ API do I just do:

```
Graph *g = <...>;
g->attr["grad_ys"] = ys;
g->attr["grad_xs"] = xs;
...
```

**Comment by tqchen** [comment]
They should be std::vector<NodeEntry> in C++ side.

**Comment by tqchen** [comment]
see https://github.com/dmlc/nnvm/blob/master/include/nnvm/pass_functions.h#L134

**Comment by slayton58** [comment]
That's ok, but the typing throughout the process is still weird, or I'm missing something that could make life easier for me. This process feels very convoluted, and I'm having to mix and match the C and C++ APIs, as no single place provides everything I need (or effectively copy code from the C API functions, which isn't ideal either)

My current plan:

xs_grad: Use `NNSymbolListInputVariables` to get the input symbols, group them using `NNSymbolCreateGroup` and then assign to the graph using `NNGraphSetNodeEntryListAttr_`.

ys_grad: Use Graph::outputs to direct assign to the graph, as it returns a `std::vector<nnvm::NodeEntry>`

ys_grad_out_grad: Not sure yet, I don't see an easy way of getting all of the output symbols from an existing symbol or graph. I guess my driver code has to do that manually, then I have to create ones_like symbol for each output and compose them with the relevant outputs, then Group and use `NNGraphSetNodeEntryListAttr_`

Like I said, feels convoluted.

**Comment by slayton58** [comment]
Ok, new plan for ys_grad_out_grad -- I have NodeEntry for each of ys_grad, so create new nodes manually.

```
std::vector<nnvm::NodeEntry> ys_grad;
for (int i = 0; i < ys_grad.size(); ++i) {
  // get the node relating to each output
  nnvm::NodeEntry& n = ys_grad[i];
  nnvm::NodePtr& np = n.node;

  // Create a new node to store ys_grad_out_grad[i]
  nnvm::NodePtr p = nnvm::Node::Create();
  p->attrs.op = nnvm::Op::Get("ones_like");
  // input is output of ys node
  p->inputs = std::vector<nnvm::NodeEntry>{nnvm::NodeEntry{np, 0, 0}};
  // put output of this into ys_grad vector
  ys_grad.emplace_back(nnvm::NodeEntry{p, 0, 0});
}
```

**Comment by tqchen** [comment]
I would not recommending doing things from both C and C++ API.  The C++ API is aimed to be feature complete, so if there is anything missing, please point out.

- For example NNSymbolListInputVariables is redirectly to a C++ API Symbol.ListInputVariables

See mxnet's code https://github.com/dmlc/mxnet/blob/nnvm/src/executor/graph_executor.cc#L155 which completely relies on C++ API for gradient

**Comment by tqchen** [comment]
The reason that front-end typing of ys_grad is symbol group is due to the fact that NodeEntry is not directly exposed in the front-end, so it is rather a hacky way to ease test and quick development, that is why NNGraphSetNodeEntryListAttr_ begins with an underscore.

**Comment by slayton58** [comment]
Ok, thanks - the code from mxnet was really useful for getting mine going.

It seems to be creating reasonable-looking graphs (bar a weird circular dependency in one spot that's to do with my driver code), so I think this one can be closed now.

I was using the C API where possible because it had a reference use (in the python code), I'm ripping it out throughout to directly use the C++ though now.
