### ISSUE TITLE
Shape inference for gradient ops

### ISSUE THREAD

**Issue by slayton58** [dmlc/nnvm#70]
I have shape inference working for my fprop graph, but the infer shapes pass wants explicit FInferShape functions defined for each gradient operator now.

I must be missing something, as all shapes of the gradient operators can be inferred from the shapes inferred in the fprop graph- how can I get this to happen?

**Comment by tqchen** [comment]
see https://github.com/tqchen/tinyflow/blob/master/src/op_nn.cc#L80

as well as  https://github.com/dmlc/nnvm/blob/master/include/nnvm/op_attr_types.h#L107

FBackwardOutToInIndex and FBackwardInGradIndex
 
There are two attributes that you can define for backward ops that gives the correspondence of input in the forward pass, and infer shape will pick that up.

I am hoping there is a better way to solve this later, by inserting hint operators of shape constraint.

**Comment by slayton58** [comment]
How would I use these though? Using an example of a conv node, inputs: {"X", "weight", "bias"}, output {"Y"}. Conv_gradient has inputs {"Y", "dY", "weight", "bias"}, outputs: {"dX", "weight_grad", "bias_grad"}

Does this mean FBackwardOutToInIndex would be {0, 1, 2}, as in "dX" corresponds to "X", "weight_grad" corresponds to "weight" and "bias_grad" corresponds to "bias"? That's what makes sense given the name of the attribute.

But then what would FBackwardInGradIndex be?

**Comment by tqchen** [comment]
Yes your understanding of FBackwardOutToInIndex is correct.

FBackwardInGradIndex gives the index of each gradient

Say conv backward takes {"dY", "weight", "bias"}, then  FBackwardInGradIndex  would be {0},

It is used for backward inference in the gradient graph.

**Comment by slayton58** [comment]
`src/pass/infer_shape_type.cc:81: Check failed: (inode.control_deps.size()) >= (1) BackwardOp need to have control_deps to its forward op`

How are these normally generated? I notice there is `Symbol::AddControlDeps`, but it isn't called (nor is the C API version) in tinyflow or the nnvm integration into mxnet.

I now have `FBackwardOutToInIndex` and `FBackwardInGradIndex` defined for all my gradient operators.

**Comment by slayton58** [comment]
I have something (seemingly) working now, but I'm not certain I'm doing everything right, because I don't really understand what `FBackwardOutToInIndex` and `FBackwardInGradIndex` actually mean.

`FBackwardOutToInIndex` seems to map the dependencies of the output(s) of the gradient operator to the relevant output from the fprop operator. However, this must satisfy  `fnode.source->num_outputs <= size(FBackwardOutToInIndex)` This means my previous understanding was incorrect, as these was only one output from the conv_fprop node, but 3 outputs from the conv_bprop node. It also seems like [the description](https://github.com/dmlc/nnvm/blob/master/include/nnvm/op_attr_types.h#L102) is inconsistent with [the code in the pass function](https://github.com/dmlc/nnvm/blob/master/src/pass/infer_shape_type.cc#L95) (Shouldn't outputs be inputs in this line?)

`FBackwardInGradIndex` is a little more clear by default (as my fprop operators only ever return one thing, there's only one value that can be used here)

**Comment by tqchen** [comment]
FBackwardOutToInIndex maps the outputs of gradient op to the inputs of the forward operator. 
Your first understanding is correct

We do require there is an explicitly control dep to forward op in this case, see https://github.com/tqchen/tinyflow/blob/master/src/op_util.h#L115

**Comment by slayton58** [comment]
So isn't this line incorrect then? https://github.com/dmlc/nnvm/blob/master/src/pass/infer_shape_type.cc#L95

Why is fnode.outputs being used instead of the inputs?

**Comment by tqchen** [comment]
This corresponds to FBackwardInGradIndex, see https://github.com/dmlc/nnvm/blob/master/src/pass/infer_shape_type.cc#L92

It is a bit confusing since it is in the inner scope of check FBackwardOutToInIndex

**Comment by slayton58** [comment]
hmm, so it is.

I think I was getting confused between `FBackwardOutToInIndex` and `FBackwardInGradIndex` in my code, and had them reversed...

**Comment by tqchen** [comment]
@slayton58 The update in https://github.com/dmlc/nnvm/pull/85 removes the need of declaring the two attributes, instead automatically guess that from the gradient function.
