### ISSUE TITLE
where and when does graph call the calc of op's back propagation?

### ISSUE THREAD

**Issue by tornadomeet** [dmlc/nnvm#74]
As the title , My current understanding is:
first, one op should set FGradient by```set_attr<FGradient>(...)```.   
then when doing gradient graph pass, it will call the FGradient funtion at this line: https://github.com/dmlc/nnvm/blob/master/src/pass/gradient.cc#L118  
FGradient owns the following format:
```c++
using FGradient = std::function<std::vector<NodeEntry>(
    const NodePtr& nodeptr,
    const std::vector<NodeEntry>& out_grads)>;
}
```
it will return one vector of NodeEntry, and i found in example/src/operator.cc(such as https://github.com/dmlc/nnvm/blob/master/example/src/operator.cc#L186) and tinyflow(such as https://github.com/tqchen/tinyflow/blob/master/src/op_tensor.cc#L200), it only create some NodeEntry variable but it doesn't t do any real calculate about back-propagation(copy gradietn in the above 2 FGradient examples), though the input NodeEntry of this variable is what the gradient(Node) should taken from.

**so if one op is more complicated(such as convolution), then when and where does back-propagation will happen?or how this happen in nnvm? and what's the connections between op's backprop with**```set_attr<FGradient>(...)``` and ```gradient pass```?  

thanks!

**Comment by tqchen** [comment]
The Gradient pass generate another graph node, that represents the backward computation. The backward will happen when these gradient node get executed.

So the "backprop" in nnvm graph is simply executing the graph(with backward nodes) in the forward manner

**Comment by tornadomeet** [comment]
so the real "backprop" will happen with the exector and gradient pass only generate one graph represent bp like fp.
