### ISSUE TITLE
Support Caffe-style input

### ISSUE THREAD

**Issue by cque7** [dmlc/nnvm#75]
Hello maintainers,
  Is there a plan to support Caffe-style protobuf front end in NNVM? I am thinking to refactor multi node @ BVLC/caffe#3441 based on nnvm so it can support more front ends.

**Comment by tqchen** [comment]
I think it could be interesting to add a proto-load pass as plugin to convert caffe graph into NNVM graph. There hasn't been effort on it. But you are more than welcomed to contribute!

This being said. I think an easier way is to simply support caffe is to use NNVM to build a pycaffe style interface

**Comment by cque7** [comment]
@tqchen Thanks for the reply. Most of our current use cases are based on prototxt input, I'd take a deeper look at NNVM and try to submit a PR for prototxt as a first step. 

If you have preferences / suggestions on how it can be done, please let me know, thanks!

**Comment by tqchen** [comment]
Sounds good. You can take a look at https://github.com/dmlc/nnvm/blob/master/src/pass/saveload_json.cc which could be quite related.

Since this introduce an extra dependency. I suggest we put it under nnvm/plugin/proto to enable optional proto serialization and deserialization pass.

**Comment by cque7** [comment]
@tqchen it looks implementing proto parsing on top of NNVM is more convenient. Do you have plan to support model parallel in NNVM? e.g. split a graph into several sub graphs, then each sub graph can run in different device / nodes. 

I did a prototype of model parallel based on Caffe solver in BVLC/caffe#3441 and it seems this works pretty well in our multi node test.

**Comment by tqchen** [comment]
Yes, I think model parallel and partitioning  is an separate issue from this one. @jermainewang  have some advanced pass to be released on this
