### ISSUE TITLE
Dmlc-core headers duplicated between modules is problematic and potentially dangerous

### ISSUE THREAD

**Issue by cjolivier01** [dmlc/nnvm#98]
Some packages (ie NNVM and PS-Lite, for instance) have some dmlc-core headers duplicated.  Problems include (but are not limited to):
  1) Improvements made in a submodule's copy may not be propagated to dmlc-core or other submodules
  2) As versions diverge, it can cause hard-to-resolve bugs and behavior, since at link-time, common functions in each build with the same signature will not always come from the same header file, even though the code may have changed in one but not the other
  3) Addition, deletion, renaming, or reordering of a virtual function in one header changes the virtual table and these can get out of sync, resulting in crashes and possibly pure virtual function calls.
  4) SDK deployment problems due to duplicate header files meant to be deployed in the same location

I would like to propose that dmlc-core headers be removed from all submodules and dmlc-core be added as a direct dependency to these submodules' repositories similarly to how it is a recursive dependency of mxnet.

Or even better, absorb NNVM, PS-Lite, tc. into a single mxnet build tree and use a common Dmlc-core, which is also absorbed.

**Comment by tqchen** [comment]
I think we can go with submodule depdendency, and optionally re-specify the dmlc-core path in submodule build.

dmlc-core is used by multiple packages, some of them unrelated to mxnet. e.g. https://github.com/dmlc/xgboost so it makes .

**Comment by tqchen** [comment]
In fact, maybe a simpler solution is to move dmlc out from include into a separate folder, say dmlc-core, then allow optionally configure the path. This will have same effect described in last comment.

**Comment by tqchen** [comment]
The key is to only allow one version of dmlc-core in search path

**Comment by cjolivier01** [comment]
I feel that leaving two copies, even in different paths for optional choosing is still error prone and generally bad practice.  I think the submodule dependency thing is good idea. wdyt?

**Comment by tqchen** [comment]
I am fine with the submodule

**Comment by tqchen** [comment]
@cjolivier01 Let us proceed with the submodule option, mind submit a PR for the change?

**Comment by cjolivier01** [comment]
Yes, I will submit this week.

**Comment by cjolivier01** [comment]
Submitted
